package pl.mpak.orbada.oracle.dba.gui.wizards;

import javax.swing.DefaultComboBoxModel;
import pl.mpak.orbada.oracle.dba.OrbadaOracleDbaPlugin;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.util.QueryUtil;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.StringUtil;

/**
 *
 * @author  akaluza
 */
public class AlterSetParameterWizard extends SqlCodeWizardPanel {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOracleDbaPlugin.class);

  private Database database;
  private String paramName;
  private Integer inst_id;
  private int paramType;
  private boolean instanceModifiable;
  
  /** Creates new form FlashbackObjectWizardPanel
   * @param database
   */
  public AlterSetParameterWizard(Database database, Integer inst_id, String paramName) {
    this.database = database;
    this.paramName = paramName;
    this.inst_id = inst_id;
    initComponents();
    init();
  }
  
  private void init() {
  }
  
  public void wizardShow() {
    Query query = database.createQuery();
    try {
      query.open("select distinct name from gv$parameter order by name");
      comboParams.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      comboParams.setSelectedItem(paramName);
      if (StringUtil.toBoolean(database.getUserProperties().getProperty("Ora10+"))) {
        query.setSqlText("select value from gv$parameter_valid_values where inst_id = :inst_id and name = :name order by ordinal");
        query.paramByName("inst_id").setInteger(inst_id);
        query.paramByName("name").setString(paramName);
        query.open();
        if (!query.eof()) {
          comboValue.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
        }
      }
      query.setSqlText("select value, type, isinstance_modifiable from gv$parameter where inst_id = :inst_id and name = :name");
      query.paramByName("inst_id").setInteger(inst_id);
      query.paramByName("name").setString(paramName);
      query.open();
      paramType = query.fieldByName("type").getInteger();
      instanceModifiable = StringUtil.toBoolean(query.fieldByName("isinstance_modifiable").getString());
      if (query.fieldByName("type").getInteger() == 1) {
        comboValue.setModel(new DefaultComboBoxModel(new Object[] {"TRUE", "FALSE"}));
      }
      if (!StringUtil.toBoolean(database.getUserProperties().getProperty("rac-detect", "false")) || !instanceModifiable) {
        comboInstances.setEnabled(false);
        labelInstances.setEnabled(false);
      }
      comboValue.setText(query.fieldByName("value").getString());
      query.open("select instance_name name from gv$instance union all select '*' name from dual order by name");
      comboInstances.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      comboInstances.setText("*");
    }
    catch (Exception ex) {
      ExceptionUtil.processException(ex);
    }
    finally {
      query.close();
    }
  }
  
  public String getDialogTitle() {
    return stringManager.getString("AlterSetParameterWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("AlterSetParameterWizard-tab-title");
  }
  
  public String getSqlCode() {
    String paramValue = comboValue.getText().trim();
    if (paramType == 2 || paramType == 4) {
      if (paramValue.length() == 0 || paramValue.charAt(0) != '\'') {
        paramValue = "'" +paramValue +"'";
      }
    }
    getResultMap().put("object_name", comboParams.getText());
    return
      "ALTER SYSTEM SET " +comboParams.getSelectedItem().toString() +" = " +paramValue +
      (!"".equals(editComment.getText()) ? "\n  COMMENT = '" +editComment.getText() +"'" : "") +
      "\n  SCOPE = " +(radioBoth.isSelected() ? "BOTH" : (radioMemory.isSelected() ? "MEMORY" : "SPFILE")) +
      (comboInstances.isEnabled() ? "\n  SID = '" +comboInstances.getText() +"'" : "");
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    groupScope = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    comboParams = new pl.mpak.sky.gui.swing.comp.ComboBox();
    comboValue = new pl.mpak.sky.gui.swing.comp.ComboBox();
    labelInstances = new javax.swing.JLabel();
    comboInstances = new pl.mpak.sky.gui.swing.comp.ComboBox();
    labelInstances1 = new javax.swing.JLabel();
    editComment = new pl.mpak.sky.gui.swing.comp.TextField();
    radioMemory = new javax.swing.JRadioButton();
    radioSpfile = new javax.swing.JRadioButton();
    radioBoth = new javax.swing.JRadioButton();
    labelInstances2 = new javax.swing.JLabel();

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText(stringManager.getString("parameter-name-dd")); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("values-dd")); // NOI18N

    comboParams.setEnabled(false);

    comboValue.setEditable(true);

    labelInstances.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelInstances.setText(stringManager.getString("instance-dd")); // NOI18N

    comboInstances.setEditable(true);

    labelInstances1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelInstances1.setText(stringManager.getString("update-comment-dd")); // NOI18N

    groupScope.add(radioMemory);
    radioMemory.setText("MEMORY");

    groupScope.add(radioSpfile);
    radioSpfile.setSelected(true);
    radioSpfile.setText("SPFILE");

    groupScope.add(radioBoth);
    radioBoth.setText("BOTH");

    labelInstances2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelInstances2.setText(stringManager.getString("scope-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelInstances, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
          .addComponent(labelInstances2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
          .addComponent(labelInstances1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(comboValue, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
          .addComponent(editComment, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
          .addComponent(comboInstances, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(radioMemory)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(radioSpfile)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(radioBoth))
          .addComponent(comboParams, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(comboParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelInstances1)
          .addComponent(editComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioMemory)
          .addComponent(radioSpfile)
          .addComponent(radioBoth)
          .addComponent(labelInstances2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboInstances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelInstances))
        .addContainerGap(47, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.comp.ComboBox comboInstances;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboParams;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboValue;
  private pl.mpak.sky.gui.swing.comp.TextField editComment;
  private javax.swing.ButtonGroup groupScope;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel labelInstances;
  private javax.swing.JLabel labelInstances1;
  private javax.swing.JLabel labelInstances2;
  private javax.swing.JRadioButton radioBoth;
  private javax.swing.JRadioButton radioMemory;
  private javax.swing.JRadioButton radioSpfile;
  // End of variables declaration//GEN-END:variables
  
}
