/*
 * TableColumns.java
 *
 * Created on 28 paŸdziernik 2007, 17:43
 */

package pl.mpak.orbada.universal.gui.tables;

import java.io.IOException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import pl.mpak.orbada.plugins.IViewAccesibilities;
import pl.mpak.orbada.gui.ITabObjectInfo;
import pl.mpak.orbada.universal.OrbadaUniversalPlugin;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.UseDBException;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.gui.swing.QueryTableCellRenderer;
import pl.mpak.usedb.gui.swing.QueryTableColumn;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.StringUtil;

/**
 *
 * @author  akaluza
 */
public class TableColumnsPanel extends javax.swing.JPanel implements ITabObjectInfo {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaUniversalPlugin.class);

  private IViewAccesibilities accesibilities;
  private String currentCatalogName;
  private String currentSchemaName = "";
  private String currentTableName = "";
  private boolean isView;
  private boolean requestRefresh = false;
  private boolean closing = false;
  
  /** Creates new form TableColumns
   * @param accesibilities
   */
  public TableColumnsPanel(IViewAccesibilities accesibilities) {
    this(accesibilities, false);
  }
  
  public TableColumnsPanel(IViewAccesibilities accesibilities, boolean isView) {
    this.accesibilities = accesibilities;
    this.isView = isView;
    initComponents();
    init();
  }
  
  private void init() {
    tableColumns.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
      public void valueChanged(ListSelectionEvent e) {
        int rowIndex = tableColumns.getSelectedRow();
        if (rowIndex >= 0 && tableColumns.getQuery().isActive()) {
          try {
            tableColumns.getQuery().getRecord(rowIndex);
          } catch (Exception ex) {
            ExceptionUtil.processException(ex);
          }
        }
      }
    });
    
    tableColumns.getQuery().setDatabase(getDatabase());
    try {
      tableColumns.getQuery().setFlushMode(Query.FlushMode.fmSynch);
    } catch (UseDBException useDBException) {
    }
    try {
      tableColumns.addColumn(new QueryTableColumn("ORDINAL_POSITION", stringManager.getString("pos"), 30));
      tableColumns.addColumn(new QueryTableColumn("COLUMN_NAME", stringManager.getString("column-name"), 150, new QueryTableCellRenderer(java.awt.Font.BOLD)));
      tableColumns.addColumn(new QueryTableColumn("TYPE_NAME", stringManager.getString("column-type"), 150, new QueryTableCellRenderer(SwingUtil.Color.GREEN)));
      tableColumns.addColumn(new QueryTableColumn("COLUMN_SIZE", stringManager.getString("size"), 60));
      tableColumns.addColumn(new QueryTableColumn("DECIMAL_DIGITS", stringManager.getString("precision"), 60));
      tableColumns.addColumn(new QueryTableColumn("IS_NULLABLE", stringManager.getString("null-q"), 30));
      tableColumns.addColumn(new QueryTableColumn("REMARKS", stringManager.getString("comment"), 300));
      //tableColumns.addColumn(new QueryTableColumn("IS_AUTOINCREMENT", "AutoInc?", 40));
    } catch (Exception ex) {
      ExceptionUtil.processException(ex);
    }
  }
  
  public Database getDatabase() {
    return accesibilities.getDatabase();
  }
  
  public void refresh() {
    try {
      requestRefresh = false;
      tableColumns.getQuery().close();
      tableColumns.getQuery().setResultSet(getDatabase().getMetaData().getColumns(currentCatalogName, currentSchemaName, currentTableName, null));
      if (!tableColumns.getQuery().isEmpty()) {
        tableColumns.changeSelection(0, 0);
      }
    } catch (Exception ex) {
      ExceptionUtil.processException(ex);
    }
  }
  
  public void refresh(String catalogName, String schemaName, String objectName) {
    if (!StringUtil.equals(catalogName, currentCatalogName) || !StringUtil.equals(schemaName, currentSchemaName) || !currentTableName.equals(objectName) || requestRefresh) {
      currentCatalogName = catalogName;
      currentSchemaName = schemaName;
      currentTableName = objectName;
      if (isVisible()) {
        refresh();
      }
      else {
        requestRefresh = true;
      }
    }
  }
  
  @Override
  public boolean canClose() {
    return true;
  }

  public void close() throws IOException {
    closing = true;
    tableColumns.getQuery().close();
    accesibilities = null;
  }
  
  public String getTitle() {
    return stringManager.getString("TableColumnsPanel-title");
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmRefresh = new pl.mpak.sky.gui.swing.Action();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableColumns = new pl.mpak.orbada.gui.comps.table.ViewTable();
    statusBarColumns = new pl.mpak.usedb.gui.swing.QueryTableStatusBar();
    toolBarColumns = new javax.swing.JToolBar();
    buttonRefresh = new pl.mpak.sky.gui.swing.comp.ToolButton();

    cmRefresh.setSmallIcon(pl.mpak.sky.gui.swing.ImageManager.getImage("/pl/mpak/res/icons/refresh16.gif")); // NOI18N
    cmRefresh.setText(stringManager.getString("cmRefresh-text")); // NOI18N
    cmRefresh.setTooltip(stringManager.getString("cmRefresh-hint")); // NOI18N
    cmRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmRefreshActionPerformed(evt);
      }
    });

    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    setLayout(new java.awt.BorderLayout());

    jScrollPane1.setViewportView(tableColumns);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);

    statusBarColumns.setShowFieldType(false);
    statusBarColumns.setShowOpenTime(false);
    statusBarColumns.setTable(tableColumns);
    add(statusBarColumns, java.awt.BorderLayout.PAGE_END);

    toolBarColumns.setFloatable(false);
    toolBarColumns.setRollover(true);

    buttonRefresh.setAction(cmRefresh);
    buttonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    buttonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    toolBarColumns.add(buttonRefresh);

    add(toolBarColumns, java.awt.BorderLayout.NORTH);
  }// </editor-fold>//GEN-END:initComponents

  private void cmRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmRefreshActionPerformed
    refresh();
}//GEN-LAST:event_cmRefreshActionPerformed
  
private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
  if (requestRefresh && !closing) {
    refresh();
  }
}//GEN-LAST:event_formComponentShown


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.comp.ToolButton buttonRefresh;
  private pl.mpak.sky.gui.swing.Action cmRefresh;
  private javax.swing.JScrollPane jScrollPane1;
  private pl.mpak.usedb.gui.swing.QueryTableStatusBar statusBarColumns;
  private pl.mpak.orbada.gui.comps.table.ViewTable tableColumns;
  private javax.swing.JToolBar toolBarColumns;
  // End of variables declaration//GEN-END:variables

}
