/*
 * RequestSuggestionDialog.java
 *
 * Created on 11 styczeñ 2009, 15:19
 */

package orbada.gui.webapp;

import javax.swing.JComponent;
import orbada.Consts;
import orbada.core.Application;
import pl.mpak.orbada.plugins.IWebAppAccessibilities;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.StringUtil;
import pl.mpak.util.task.Task;
import pl.mpak.util.task.TaskPool;
import pl.mpak.waitdlg.WaitDialog;

/**
 *
 * @author  akaluza
 */
public class RequestProblemDialog extends javax.swing.JDialog {

  private final static StringManager stringManager = StringManagerFactory.getStringManager(Consts.class);

  /** Creates new form RequestSuggestionDialog */
  public RequestProblemDialog() {
    super(SwingUtil.getRootFrame(), false);
    initComponents();
    init();
  }
  
  private void init() {
    textContent.setFont(textTitle.getFont());
    textPath.setFont(textTitle.getFont());
    textWorkaround.setFont(textTitle.getFont());
    textHelpCode.setFont(textHelpCode.getFont().deriveFont((float)getFont().getSize()));
    textOs.setText(System.getProperty("os.name") + ", " + System.getProperty("os.version"));
    textJava.setText(System.getProperty("java.vendor") + ", " + System.getProperty("java.version"));
    
    getRootPane().setDefaultButton(buttonOk);
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmCancel.getShortCut(), "cmCancel");
    getRootPane().getActionMap().put("cmCancel", cmCancel);
    SwingUtil.centerWithinScreen(this);
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        textContent.requestFocusInWindow();
      }
    });
  }
  
  public static void showDialog() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        RequestProblemDialog dialog = new RequestProblemDialog();
        dialog.setVisible(true);
      }
    });
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmOk = new pl.mpak.sky.gui.swing.Action();
    cmCancel = new pl.mpak.sky.gui.swing.Action();
    buttonOk = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    labelTitle = new javax.swing.JLabel();
    textTitle = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel5 = new javax.swing.JLabel();
    textOs = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel6 = new javax.swing.JLabel();
    textJava = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel7 = new javax.swing.JLabel();
    textDatabase = new pl.mpak.sky.gui.swing.comp.TextField();
    labelContent = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    textContent = new pl.mpak.sky.gui.swing.comp.TextArea();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    textPath = new pl.mpak.sky.gui.swing.comp.TextArea();
    jPanel2 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    textWorkaround = new pl.mpak.sky.gui.swing.comp.TextArea();
    jPanel3 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jScrollPane5 = new javax.swing.JScrollPane();
    textHelpCode = new pl.mpak.sky.gui.swing.comp.TextArea();

    cmOk.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
    cmOk.setText(stringManager.getString("cmOk-text")); // NOI18N
    cmOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmOkActionPerformed(evt);
      }
    });

    cmCancel.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmCancel.setText(stringManager.getString("cmCancel-text")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("RequestProblemDialog-title")); // NOI18N

    buttonOk.setAction(cmOk);
    buttonOk.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonOk.setPreferredSize(new java.awt.Dimension(85, 25));

    buttonCancel.setAction(cmCancel);
    buttonCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonCancel.setPreferredSize(new java.awt.Dimension(85, 25));

    jLabel1.setText(stringManager.getString("RequestProblemDialog-field-required")); // NOI18N

    labelTitle.setText(stringManager.getString("RequestProblemDialog-short-description")); // NOI18N
    labelTitle.setEnabled(false);

    textTitle.setEditable(false);

    jLabel5.setText(stringManager.getString("RequestProblemDialog-os")); // NOI18N

    jLabel6.setText(stringManager.getString("RequestProblemDialog-java-version")); // NOI18N

    jLabel7.setText(stringManager.getString("RequestProblemDialog-database")); // NOI18N

    labelContent.setText(stringManager.getString("RequestProblemDialog-describe-problem")); // NOI18N

    textContent.setLineWrap(true);
    textContent.setWrapStyleWord(true);
    jScrollPane1.setViewportView(textContent);

    jLabel8.setText(stringManager.getString("RequestProblemDialog-problem-frequency")); // NOI18N

    textPath.setLineWrap(true);
    textPath.setWrapStyleWord(true);
    jScrollPane3.setViewportView(textPath);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(textDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(textJava, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(textOs, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(textTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(labelTitle)
          .addComponent(jLabel5)
          .addComponent(jLabel6)
          .addComponent(jLabel7)
          .addComponent(labelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
          .addComponent(jScrollPane3))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelTitle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelContent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab(stringManager.getString("RequestProblemDialog-problem"), jPanel1); // NOI18N

    jLabel4.setText(stringManager.getString("RequestProblemDialog-problem-workaround")); // NOI18N

    textWorkaround.setLineWrap(true);
    textWorkaround.setWrapStyleWord(true);
    jScrollPane2.setViewportView(textWorkaround);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2)
          .addComponent(jLabel4))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab(stringManager.getString("RequestProblemDialog-known-solution"), jPanel2); // NOI18N

    jLabel9.setText(stringManager.getString("RequestProblemDialog-problem-solution-description")); // NOI18N

    textHelpCode.setLineWrap(true);
    textHelpCode.setWrapStyleWord(true);
    textHelpCode.setFont(new java.awt.Font("Courier New", 0, 9));
    jScrollPane5.setViewportView(textHelpCode);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab(stringManager.getString("RequestProblemDialog-helpful-code"), jPanel3); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void cmOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmOkActionPerformed
//  if (StringUtil.isEmpty(textTitle.getText())) {
//    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestProblemDialog-title-required"), ModalResult.OK, MessageBox.ERROR);
//    return;
//  }
  if (StringUtil.isEmpty(textOs.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestProblemDialog-os-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  if (StringUtil.isEmpty(textJava.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestProblemDialog-java-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  if (StringUtil.isEmpty(textContent.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestProblemDialog-problem-description"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  if (StringUtil.isEmpty(textPath.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestProblemDialog-frequency-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  cmOk.setEnabled(false);
  TaskPool.getTaskPool().addTask(new Task(stringManager.getString("RequestProblemDialog-request-registering")) {
    String title = textTitle.getText();
    String content = 
      "(DESCRIPTION)\n" +textContent.getText() +"\n" +
      "(HELP CODE)\n" +(StringUtil.isEmpty(textHelpCode.getText()) ? "N/A" : ("<code>" +textHelpCode.getText() +"</code>"));
    String path = textPath.getText();
    String os = textOs.getText();
    String db = textDatabase.getText();
    String java = textJava.getText();
      @Override
    public void run() {
      WaitDialog.showWaitDialog(stringManager.getString("RequestProblemDialog-sending-request"));
      try {
        Application.get().getWebAppAccessibilities().requestPost(IWebAppAccessibilities.PROBLEM, title, os, db, null, java, path, null, content, textWorkaround.getText());
      }
      finally {
        cmOk.setEnabled(true);
        WaitDialog.hideWaitDialog();
      }
      //MessageBox.show(stringManager.getString("RequestProblemDialog-request"), stringManager.getString("RequestProblemDialog-request-id"));
      RequestProblemDialog.this.dispose();
    }
  });
}//GEN-LAST:event_cmOkActionPerformed

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  dispose();
}//GEN-LAST:event_cmCancelActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private pl.mpak.sky.gui.swing.Action cmOk;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel labelContent;
  private javax.swing.JLabel labelTitle;
  private pl.mpak.sky.gui.swing.comp.TextArea textContent;
  private pl.mpak.sky.gui.swing.comp.TextField textDatabase;
  private pl.mpak.sky.gui.swing.comp.TextArea textHelpCode;
  private pl.mpak.sky.gui.swing.comp.TextField textJava;
  private pl.mpak.sky.gui.swing.comp.TextField textOs;
  private pl.mpak.sky.gui.swing.comp.TextArea textPath;
  private pl.mpak.sky.gui.swing.comp.TextField textTitle;
  private pl.mpak.sky.gui.swing.comp.TextArea textWorkaround;
  // End of variables declaration//GEN-END:variables

}
