rm ./orbada-waitdlg/orbada-waitdlg.iml
rm ./orbada-meld-diff/orbada-meld-diff.iml
rm ./orbada-plugin-postgresql/orbada-postgresql.iml
rm ./orbada-plugins/orbada-plugins.iml
rm ./orbada-plugin-welcome/orbada-welcome.iml
rm ./orbada-g2/orbada-g2.iml
rm ./orbada-gadgets/orbada-gadgets.iml
rm ./orbada-mysql-autocomplete/orbada-mysql-autocomplete.iml
rm ./orbada-hsqldb/orbada-hsqldb.iml
rm ./orbada-plugin-reports/orbada-reports.iml
rm ./orbada-firebird-autocomplete/orbada-firebird-autocomplete.iml
rm ./orbada-export-csv/orbada-export-csv.iml
rm ./orbada-adder/orbada-adder.iml
rm ./orbada-plugin-dancer-pw/orbada-dancer-pw.iml
rm ./plugin-modules/orbada-beanshell/orbada-beanshell.iml
rm ./orbada-plugin-sql-scripts/orbada-sql-scripts.iml
rm ./orbada-laf-nimrod/orbada-laf-nimrod.iml
rm ./orbada-prop/orbada-prop.iml
rm ./orbada-plugin-programmers/orbada-programmers.iml
rm ./orbada-json-data-view/orbada-json-data-view.iml
rm ./orbada-res/orbada-res.iml
rm ./orbada-dml-format/orbada-dml-format.iml
rm ./orbada-editor-savecontent/orbada-editor-savecontent.iml
rm ./plugin/orbada-snippets/orbada-snippets.iml
rm ./plugin/orbada-snippets/plugin-modules-orbada-snippets.iml
rm ./plugin/orbada-meld-diff/plugin-modules-orbada-meld-diff.iml
rm ./plugin/orbada-meld-diff/orbada-meld-diff.iml
rm ./plugin/orbada-meld-diff/plugin-orbada-meld-diff.iml
rm ./plugin/orbada-welcome/plugin-modules-orbada-welcome.iml
rm ./plugin/orbada-welcome/orbada-welcome.iml
rm ./plugin/orbada-gadgets/orbada-gadgets.iml
rm ./plugin/orbada-gadgets/plugin-modules-orbada-gadgets.iml
rm ./plugin/orbada-gadgets/plugin-orbada-gadgets.iml
rm ./plugin/plugin.iml
rm ./plugin/orbada-mysql-autocomplete/orbada-mysql-autocomplete.iml
rm ./plugin/orbada-mysql-autocomplete/plugin-modules-orbada-mysql-autocomplete.iml
rm ./plugin/orbada-mysql-autocomplete/plugin-orbada-mysql-autocomplete.iml
rm ./plugin/orbada-postgresql/orbada-postgresql.iml
rm ./plugin/orbada-postgresql/plugin-modules-orbada-postgresql.iml
rm ./plugin/orbada-sql-scripts/orbada-sql-scripts.iml
rm ./plugin/orbada-sql-scripts/plugin-modules-orbada-sql-scripts.iml
rm ./plugin/orbada-hsqldb/plugin-modules-orbada-hsqldb.iml
rm ./plugin/orbada-hsqldb/plugin-orbada-hsqldb.iml
rm ./plugin/orbada-hsqldb/orbada-hsqldb.iml
rm ./plugin/orbada-firebird-autocomplete/orbada-firebird-autocomplete.iml
rm ./plugin/orbada-firebird-autocomplete/plugin-modules-orbada-firebird-autocomplete.iml
rm ./plugin/orbada-firebird-autocomplete/plugin-orbada-firebird-autocomplete.iml
rm ./plugin/orbada-export-csv/plugin-modules-orbada-export-csv.iml
rm ./plugin/orbada-export-csv/orbada-export-csv.iml
rm ./plugin/orbada-export-csv/plugin-orbada-export-csv.iml
rm ./plugin/orbada-adder/orbada-plugin-adder.iml
rm ./plugin/orbada-sqlite/plugin-modules-orbada-sqlite.iml
rm ./plugin/orbada-sqlite/orbada-sqlite.iml
rm ./plugin/orbada-laf-nimrod/plugin-modules-orbada-laf-nimrod.iml
rm ./plugin/orbada-laf-nimrod/orbada-laf-nimrod.iml
rm ./plugin/orbada-laf-nimrod/plugin-orbada-laf-nimrod.iml
rm ./plugin/orbada-universal/orbada-universal.iml
rm ./plugin/orbada-universal/plugin-modules-orbada-universal.iml
rm ./plugin/orbada-json-data-view/orbada-json-data-view.iml
rm ./plugin/orbada-json-data-view/plugin-orbada-json-data-view.iml
rm ./plugin/orbada-json-data-view/plugin-modules-orbada-json-data-view.iml
rm ./plugin/orbada-dml-format/plugin-modules-orbada-dml-format.iml
rm ./plugin/orbada-dml-format/plugin-orbada-dml-format.iml
rm ./plugin/orbada-dml-format/orbada-dml-format.iml
rm ./plugin/orbada-editor-savecontent/plugin-modules-orbada-editor-savecontent.iml
rm ./plugin/orbada-editor-savecontent/orbada-editor-savecontent.iml
rm ./plugin/orbada-editor-savecontent/plugin-orbada-editor-savecontent.iml
rm ./plugin/orbada-reports/plugin-modules-orbada-reports.iml
rm ./plugin/orbada-reports/orbada-reports.iml
rm ./plugin/orbada-oracle/plugin-orbada-oracle.iml
rm ./plugin/orbada-oracle/orbada-oracle.iml
rm ./plugin/orbada-oracle/plugin-modules-orbada-oracle.iml
rm ./plugin/orbada-export-excel/plugin-orbada-export-excel.iml
rm ./plugin/orbada-export-excel/orbada-export-excel.iml
rm ./plugin/orbada-export-excel/plugin-modules-orbada-export-excel.iml
rm ./plugin/orbada-programmers/plugin-modules-orbada-programmers.iml
rm ./plugin/orbada-programmers/orbada-programmers.iml
rm ./plugin/orbada-firebird/plugin-orbada-firebird.iml
rm ./plugin/orbada-firebird/plugin-modules-orbada-firebird.iml
rm ./plugin/orbada-firebird/orbada-firebird.iml
rm ./plugin/orbada-oracle-edt/plugin-orbada-oracle-edt.iml
rm ./plugin/orbada-oracle-edt/orbada-oracle-edt.iml
rm ./plugin/orbada-oracle-edt/plugin-modules-orbada-oracle-edt.iml
rm ./plugin/orbada-dancer-pw/orbada-dancer-pw.iml
rm ./plugin/orbada-export-pdf/orbada-export-pdf.iml
rm ./plugin/orbada-export-pdf/plugin-modules-orbada-export-pdf.iml
rm ./plugin/orbada-export-pdf/plugin-orbada-export-pdf.iml
rm ./plugin/orbada-tray/orbada-tray.iml
rm ./plugin/orbada-tray/plugin-modules-orbada-tray.iml
rm ./plugin/orbada-export-dbf/plugin-modules-orbada-export-dbf.iml
rm ./plugin/orbada-export-dbf/plugin-orbada-export-dbf.iml
rm ./plugin/orbada-export-dbf/orbada-export-dbf.iml
rm ./plugin/orbada-todo/plugin-modules-orbada-todo.iml
rm ./plugin/orbada-todo/orbada-todo.iml
rm ./plugin/orbada-oracle-tune/plugin-modules-orbada-oracle-tune.iml
rm ./plugin/orbada-oracle-tune/orbada-oracle-tune.iml
rm ./plugin/orbada-oracle-tune/plugin-orbada-oracle-tune.iml
rm ./plugin/orbada-laf-tinylaf/plugin-modules-orbada-laf-tinylaf.iml
rm ./plugin/orbada-laf-tinylaf/plugin-orbada-laf-tinylaf.iml
rm ./plugin/orbada-laf-tinylaf/orbada-laf-tinylaf.iml
rm ./plugin/orbada-import-csv/plugin-modules-orbada-import-csv.iml
rm ./plugin/orbada-import-csv/plugin-orbada-import-csv.iml
rm ./plugin/orbada-import-csv/orbada-import-csv.iml
rm ./plugin/orbada-data-move/orbada-data-move.iml
rm ./plugin/orbada-xml-data-view/orbada-xml-data-view.iml
rm ./plugin/orbada-xml-data-view/plugin-modules-orbada-xml-data-view.iml
rm ./plugin/orbada-system/plugin-modules-orbada-system.iml
rm ./plugin/orbada-system/orbada-system.iml
rm ./plugin/orbada-derbydb/orbada-derbydb.iml
rm ./plugin/orbada-derbydb/plugin-modules-orbada-derbydb.iml
rm ./plugin/orbada-derbydb/plugin-orbada-derbydb.iml
rm ./plugin/orbada-beanshell/orbada-beanshell.iml
rm ./plugin/orbada-beanshell/orbada-plugin-beanshell.iml
rm ./plugin/orbada-export-data-text/plugin-orbada-export-data-text.iml
rm ./plugin/orbada-export-data-text/orbada-export-data-text.iml
rm ./plugin/orbada-export-data-text/plugin-modules-orbada-export-data-text.iml
rm ./plugin/orbada-laf-jgoodies/plugin-orbada-laf-jgoodies.iml
rm ./plugin/orbada-laf-jgoodies/plugin-modules-orbada-laf-jgoodies.iml
rm ./plugin/orbada-laf-jgoodies/orbada-laf-jgoodies.iml
rm ./plugin/orbada-oracle-dba/orbada-oracle-dba.iml
rm ./plugin/orbada-oracle-dba/plugin-orbada-oracle-dba.iml
rm ./plugin/orbada-oracle-dba/plugin-modules-orbada-oracle-dba.iml
rm ./plugin/orbada-jaybird/plugin-orbada-jaybird.iml
rm ./plugin/orbada-jaybird/orbada-jaybird.iml
rm ./plugin/orbada-jaybird/plugin-modules-orbada-jaybird.iml
rm ./plugin/orbada-laf-jtatoo/plugin-orbada-laf-jtatoo.iml
rm ./plugin/orbada-laf-jtatoo/plugin-modules-orbada-laf-jtatoo.iml
rm ./plugin/orbada-laf-jtatoo/orbada-laf-jtatoo.iml
rm ./plugin/orbada-laf-substance/plugin-modules-orbada-laf-substance.iml
rm ./plugin/orbada-laf-substance/plugin-orbada-laf-substance.iml
rm ./plugin/orbada-laf-substance/orbada-laf-substance.iml
rm ./plugin/orbada-octopus-pw/plugin-orbada-octopus-pw.iml
rm ./plugin/orbada-octopus-pw/orbada-octopus-pw.iml
rm ./plugin/orbada-octopus-pw/plugin-modules-orbada-octopus-pw.iml
rm ./plugin/orbada-sql-macro/plugin-modules-orbada-sql-macro.iml
rm ./plugin/orbada-sql-macro/orbada-sql-macro.iml
rm ./plugin/orbada-export/plugin-orbada-export.iml
rm ./plugin/orbada-export/orbada-export.iml
rm ./plugin/orbada-export/plugin-modules-orbada-export.iml
rm ./plugin/orbada-mysql/orbada-mysql.iml
rm ./plugin/orbada-mysql/plugin-modules-orbada-mysql.iml
rm ./plugin/orbada-mysql/plugin-orbada-mysql.iml
rm ./plugin/plugin-modules.iml
rm ./plugin/orbada-local-history/plugin-modules-orbada-local-history.iml
rm ./plugin/orbada-local-history/plugin-orbada-local-history.iml
rm ./plugin/orbada-local-history/orbada-local-history.iml
rm ./orbada-oracle/orbada-oracle.iml
rm ./orbada-plugin-universal/orbada-universal.iml
rm ./orbada-export-excel/orbada-export-excel.iml
rm ./orbada-sky/orbada-sky.iml
rm ./orbada-firebird/orbada-firebird.iml
rm ./orbada-plugin-data-move/orbada-data-move.iml
rm ./orbada-oracle-edt/orbada-oracle-edt.iml
rm ./orbada-export-pdf/orbada-export-pdf.iml
rm ./orbada-datatext/orbada-datatext.iml
rm ./orbada-export-dbf/orbada-export-dbf.iml
rm ./orbada-plugin-xml-data-view/orbada-xml-data-view.iml
rm ./orbada-plugin-tray/orbada-tray.iml
rm ./orbada-oracle-tune/orbada-oracle-tune.iml
rm ./orbada-plugin-system/orbada-system.iml
rm ./orbada-userdb/orbada-userdb.iml
rm ./orbada-laf-tinylaf/orbada-laf-tinylaf.iml
rm ./json/json.iml
rm ./orbada-plugin-snippets/orbada-snippets.iml
rm ./orbada-import-csv/orbada-import-csv.iml
rm ./orbada-util/orbada-util.iml
rm ./orbada/orbada-orbada.iml
rm ./orbada-derbydb/orbada-derbydb.iml
rm ./orbada-plugin-todo/orbada-todo.iml
rm ./orbada-id/orbada-id.iml
rm ./drink-master/drink-master.iml
rm ./startup/startup.iml
rm ./orbada-plugin-sql-macro/orbada-sql-macro.iml
rm ./orbada-parser/orbada-parser.iml
rm ./orbada-export-data-text/orbada-export-data-text.iml
rm ./orbada-laf-jgoodies/orbada-laf-jgoodies.iml
rm ./orbada-oracle-dba/orbada-oracle-dba.iml
rm ./orbada-jaybird/orbada-jaybird.iml
rm ./orbada-laf-jtatoo/orbada-laf-jtatoo.iml
rm ./orbada-task/orbada-task.iml
rm ./orbada-laf-substance/orbada-laf-substance.iml
rm ./orbada-octopus-pw/orbada-octopus-pw.iml
rm ./orbada-db-objects/orbada-db-objects.iml
rm ./orbada-reports-db/orbada-reports-db.iml
rm ./orbada-export/orbada-export.iml
rm ./orbada-mysql/orbada-mysql.iml
rm ./orbada-plugin-sqlite/orbada-sqlite.iml
rm ./orbada-local-history/orbada-local-history.iml
