/*
 * ViewAsStringPanel.java
 *
 * Created on 26 listopad 2007, 18:53
 */

package pl.mpak.orbada.xmldataview.gui;

import java.io.ByteArrayInputStream;
import java.io.Closeable;
import java.io.IOException;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import pl.mpak.orbada.xmldataview.OrbadaXmlDataViewPlugin;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class ViewXmlDataPanel extends javax.swing.JPanel implements Closeable {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager("xml-data-view");

  private Object value;
  
  /** Creates new form ViewAsStringPanel 
   * @param value 
   */
  public ViewXmlDataPanel(Object value) {
    this.value = value;
    initComponents();
    init();
  }
  
  private TreeModel parse(String source) throws Exception {
    SAXParserFactory factory = SAXParserFactory.newInstance();
    XMLIconTreeHandler handler = new XMLIconTreeHandler();
    SAXParser saxParser = factory.newSAXParser();
    saxParser.parse(new ByteArrayInputStream(source.getBytes()), handler);
    return new DefaultTreeModel(handler.getRoot());
  }

  private void init() {
    if (value != null) {
      try {
        treeXml.setModel(parse(value.toString()));
      } catch (Exception ex) {
        MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      }
    }
  }
  
  public void close() throws IOException {
    
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    treeXml = new javax.swing.JTree();

    setLayout(new java.awt.BorderLayout());

    treeXml.setModel(null);
    jScrollPane1.setViewportView(treeXml);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTree treeXml;
  // End of variables declaration//GEN-END:variables
  
}
