package pl.mpak.orbada.oracle.gui.jobs;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.script.SimpleSQLScript;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class JobRunWizard extends SqlCodeWizardPanel {

  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOraclePlugin.class);

  private Database database;
  private Long job;

  /** Creates new form JobRemoveWizard */
  public JobRunWizard(Database database, Long job) {
    this.database = database;
    this.job = job;
    initComponents();
    init();
  }
  
  private void init() {
    
  }
  
  public void wizardShow() {
    
  }

  public String getDialogTitle() {
    return stringManager.getString("JobRunWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("JobRunWizard-tab-title");
  }
  
  public String getSqlCode() {
    StringBuffer sb = new StringBuffer();
    sb.append("BEGIN\n");
    sb.append("  DBMS_JOB.RUN(\n");
    sb.append("    JOB => " +job);
    if (checkForce.isSelected()) {
      sb.append(",\n    FORCE => TRUE");
    }
    sb.append("\n  );\n");
    sb.append("END;\n/\n");
    return sb.toString();
  }
  
  public boolean execute() {
    SimpleSQLScript script = new SimpleSQLScript(database);
    if (!script.executeScript(getSqlCode())) {
      MessageBox.show(this, stringManager.getString("error"), script.getErrors(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
    return true;
  }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    checkForce = new javax.swing.JCheckBox();

    checkForce.setText(stringManager.getString("check-if-instance-runing")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkForce)
        .addContainerGap(177, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkForce)
        .addContainerGap(270, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkForce;
  // End of variables declaration//GEN-END:variables

}
