/*
 * ComponentActionMapDialog.java
 *
 * Created on 1 luty 2009, 15:18
 */

package orbada.gui;

import java.awt.Component;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.DefaultListModel;
import javax.swing.FocusManager;
import javax.swing.JComponent;

import orbada.Consts;
import pl.mpak.sky.gui.swing.ActionListCellRenderer;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class ComponentActionMapDialog extends javax.swing.JDialog {

  private final static StringManager stringManager = StringManagerFactory.getStringManager(Consts.class);

  /** Creates new form ComponentActionMapDialog */
  public ComponentActionMapDialog() {
    super(SwingUtil.getRootFrame(), true);
    initComponents();
    init();
  }
  
  public static void showDialog() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        ComponentActionMapDialog dialog = new ComponentActionMapDialog();
        dialog.setVisible(true);
      }
    });
  }
  
  private void init() {
    DefaultListModel model = new DefaultListModel();
    listActions.setModel(model);
    Component comp = FocusManager.getCurrentManager().getFocusOwner();
    while (comp != null) {
      if (comp instanceof JComponent) {
        ActionMap map = ((JComponent)comp).getActionMap();
        Object[] os = map.keys();
        if (os != null && os.length > 0) {
          for (Object o : os) {
            Action a = map.get(o);
            if (a.getValue(Action.ACCELERATOR_KEY) != null) {
              model.addElement(a);
            }
          }
        }
      }
      comp = comp.getParent();
    }
    listActions.setCellRenderer(new ActionListCellRenderer());
    getRootPane().setDefaultButton(buttonClose);
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmClose.getShortCut(), "cmClose");
    getRootPane().getActionMap().put("cmClose", cmClose);
    SwingUtil.centerWithinScreen(this);
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmClose = new pl.mpak.sky.gui.swing.Action();
    buttonClose = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    listActions = new javax.swing.JList();

    cmClose.setActionCommandKey("cmClose");
    cmClose.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmClose.setText(stringManager.getString("cmClose-text")); // NOI18N
    cmClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCloseActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("ComponentActionMapDialog-title")); // NOI18N

    buttonClose.setAction(cmClose);
    buttonClose.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonClose.setPreferredSize(new java.awt.Dimension(75, 23));

    listActions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    listActions.setFixedCellHeight(18);
    jScrollPane1.setViewportView(listActions);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(buttonClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void cmCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCloseActionPerformed
  dispose();
}//GEN-LAST:event_cmCloseActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonClose;
  private pl.mpak.sky.gui.swing.Action cmClose;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList listActions;
  // End of variables declaration//GEN-END:variables

}
