package pl.mpak.orbada.gui.webapp;

import java.sql.SQLException;
import javax.swing.JComponent;
import pl.mpak.orbada.Consts;
import pl.mpak.orbada.core.Application;
import pl.mpak.orbada.plugins.IWebAppAccessibilities;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.core.Database;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.StringUtil;
import pl.mpak.util.task.Task;
import pl.mpak.util.task.TaskPool;
import pl.mpak.waitdlg.WaitDialog;

/**
 *
 * @author  akaluza
 */
public class RequestErrorDialog extends javax.swing.JDialog {

  private final static StringManager stringManager = StringManagerFactory.getStringManager(Consts.class);

  private Throwable exception;
  
  /** Creates new form RequestSuggestionDialog */
  public RequestErrorDialog(Throwable exception) {
    super(SwingUtil.getRootFrame(), true);
    this.exception = exception;
    initComponents();
    init();
  }
  
  private void init() {
    textContent.setFont(textTitle.getFont());
    textCallStack.setFont(textCallStack.getFont().deriveFont((float)getFont().getSize()));
    textWorkaround.setFont(textTitle.getFont());
    
    textOs.setText(System.getProperty("os.name") + ", " + System.getProperty("os.version"));
    textJava.setText(System.getProperty("java.vendor") + ", " + System.getProperty("java.version"));
    if (Application.get().getMainFrame().getActiveDatabase() != null) {
      Database db = Application.get().getMainFrame().getActiveDatabase();
      try {
        textDatabase.setText(db.getMetaData().getDatabaseProductName() + ", " + db.getMetaData().getDatabaseProductVersion());
      } catch (SQLException ex) {
        ExceptionUtil.processException(ex);
      }
      textJdbc.setText(db.getDriver().getClass().getName() +", " +db.getDriver().getMajorVersion() +"." +db.getDriver().getMinorVersion());
    }
    if (exception != null) {
      if (exception.getCause() != null) {
        textTitle.setText(exception.getCause().getClass().getName());
      }
      else {
        textTitle.setText(exception.getClass().getName());
      }
      textCallStack.setText(ExceptionUtil.getStackTrace(exception));
    }
    
    getRootPane().setDefaultButton(buttonOk);
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmCancel.getShortCut(), "cmCancel");
    getRootPane().getActionMap().put("cmCancel", cmCancel);
    SwingUtil.centerWithinScreen(this);
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        textContent.requestFocusInWindow();
      }
    });
  }
  
  public static void showDialog(final Throwable exception) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        RequestErrorDialog dialog = new RequestErrorDialog(exception);
        dialog.setVisible(true);
      }
    });
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmOk = new pl.mpak.sky.gui.swing.Action();
    cmCancel = new pl.mpak.sky.gui.swing.Action();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    labelTitle = new javax.swing.JLabel();
    textTitle = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    textWorkaround = new pl.mpak.sky.gui.swing.comp.TextArea();
    jLabel5 = new javax.swing.JLabel();
    textOs = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel6 = new javax.swing.JLabel();
    textJava = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel7 = new javax.swing.JLabel();
    textDatabase = new pl.mpak.sky.gui.swing.comp.TextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    textContent = new pl.mpak.sky.gui.swing.comp.TextArea();
    labelContent = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    textJdbc = new pl.mpak.sky.gui.swing.comp.TextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane4 = new javax.swing.JScrollPane();
    textCallStack = new pl.mpak.sky.gui.swing.comp.TextArea();
    buttonOk = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    cmOk.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
    cmOk.setText(stringManager.getString("cmOk-text")); // NOI18N
    cmOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmOkActionPerformed(evt);
      }
    });

    cmCancel.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmCancel.setText(stringManager.getString("cmCancel-text")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("RequestErrorDialog-title")); // NOI18N

    labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelTitle.setText(stringManager.getString("RequestErrorDialog-short-description-dd")); // NOI18N
    labelTitle.setEnabled(false);

    textTitle.setEnabled(false);

    jLabel4.setText(stringManager.getString("RequestErrorDialog-problem-workaround-dd")); // NOI18N

    textWorkaround.setLineWrap(true);
    textWorkaround.setWrapStyleWord(true);
    jScrollPane2.setViewportView(textWorkaround);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText(stringManager.getString("RequestErrorDialog-os-dd")); // NOI18N

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText(stringManager.getString("RequestErrorDialog-java-version-dd")); // NOI18N

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText(stringManager.getString("RequestErrorDialog-database-dd")); // NOI18N

    textContent.setLineWrap(true);
    textContent.setWrapStyleWord(true);
    jScrollPane3.setViewportView(textContent);

    labelContent.setText(stringManager.getString("RequestErrorDialog-problem-frequency-dd")); // NOI18N

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel9.setText(stringManager.getString("RequestErrorDialog-jdbc-driver-dd")); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textOs, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textJava, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textJdbc, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
          .addComponent(labelContent, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelTitle)
          .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(textOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(textJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(textDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(textJdbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelContent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab(stringManager.getString("RequestErrorDialog-general"), jPanel1); // NOI18N

    textCallStack.setColumns(20);
    textCallStack.setRows(5);
    textCallStack.setFont(new java.awt.Font("Courier New", 0, 9));
    jScrollPane4.setViewportView(textCallStack);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab(stringManager.getString("RequestErrorDialog-error-call-stack"), jPanel2); // NOI18N

    buttonOk.setAction(cmOk);
    buttonOk.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonOk.setPreferredSize(new java.awt.Dimension(85, 25));

    buttonCancel.setAction(cmCancel);
    buttonCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonCancel.setPreferredSize(new java.awt.Dimension(85, 25));

    jLabel1.setText(stringManager.getString("RequestErrorDialog-required-fields")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
          .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void cmOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmOkActionPerformed
//  if (StringUtil.isEmpty(textTitle.getText())) {
//    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestErrorDialog-title-expected"), ModalResult.OK, MessageBox.ERROR);
//    return;
//  }
  if (StringUtil.isEmpty(textOs.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestErrorDialog-os-version-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  if (StringUtil.isEmpty(textJava.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestErrorDialog-java-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  if (StringUtil.isEmpty(textContent.getText())) {
    MessageBox.show(this, stringManager.getString("error"), stringManager.getString("RequestErrorDialog-problem-description-expected"), ModalResult.OK, MessageBox.ERROR);
    return;
  }
  TaskPool.getTaskPool().addTask(new Task(stringManager.getString("RequestErrorDialog-request-register")) {
    String title = textTitle.getText();
    String content = "(DESCRIPTION)\n" +textContent.getText();
    String os = textOs.getText();
    String db = textDatabase.getText();
    String java = textJava.getText();
    String jdbc = textJdbc.getText();
    String callStack = textCallStack.getText();
      @Override
    public void run() {
      WaitDialog.showWaitDialog(stringManager.getString("RequestErrorDialog-request-sending"));
      try {
        Application.get().getWebAppAccessibilities().requestPost(IWebAppAccessibilities.PROBLEM, title, os, db, jdbc, java, null, callStack, content, textWorkaround.getText());
      }
      finally {
        WaitDialog.hideWaitDialog();
      }
      //MessageBox.show(stringManager.getString("RequestErrorDialog-request"), stringManager.getString("RequestErrorDialog-request-id"));
      RequestErrorDialog.this.dispose();
    }
  });
}//GEN-LAST:event_cmOkActionPerformed

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  dispose();
}//GEN-LAST:event_cmCancelActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private pl.mpak.sky.gui.swing.Action cmOk;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel labelContent;
  private javax.swing.JLabel labelTitle;
  private pl.mpak.sky.gui.swing.comp.TextArea textCallStack;
  private pl.mpak.sky.gui.swing.comp.TextArea textContent;
  private pl.mpak.sky.gui.swing.comp.TextField textDatabase;
  private pl.mpak.sky.gui.swing.comp.TextField textJava;
  private pl.mpak.sky.gui.swing.comp.TextField textJdbc;
  private pl.mpak.sky.gui.swing.comp.TextField textOs;
  private pl.mpak.sky.gui.swing.comp.TextField textTitle;
  private pl.mpak.sky.gui.swing.comp.TextArea textWorkaround;
  // End of variables declaration//GEN-END:variables

}
