/*
 * ViewValueDialog.java
 *
 * Created on 26 listopad 2007, 18:28
 */

package orbada.gui.comps;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.Closeable;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.JRadioButtonMenuItem;
import orbada.Consts;
import orbada.core.Application;
import orbada.gui.comps.table.view.BeanPropertyPanel;
import orbada.gui.comps.table.view.ViewAsBinaryPanel;
import orbada.gui.comps.table.view.ViewAsHexPanel;
import orbada.gui.comps.table.view.ViewAsPicturePanel;
import orbada.gui.comps.table.view.ViewAsStringPanel;
import orbada.gui.comps.table.view.ViewHtmlPanel;
import orbada.gui.comps.table.view.cm.ViewValueServiceAction;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.plugins.providers.ViewValueProvider;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.core.QueryField;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.FileUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.variant.Variant;
import pl.mpak.util.variant.VariantType;

/**
 *
 * @author  akaluza
 */
public class ViewValueDialog extends javax.swing.JDialog {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager(Consts.class);

  private Object value;
  private Component currentPanel;
  private ISettings settings;
  
  /** Creates new form ViewValueDialog
   * @param value
   */
  public ViewValueDialog(Object value) {
    super();
    this.value = value;
    initComponents();
    init();
  }
  
  public static void show(Object value) {
    ViewValueDialog dialog = new ViewValueDialog(value);
    dialog.setVisible(true);
  }
  
  private void init() {
    settings = Application.get().getSettings("orbada-view-value-dialog");
    try {
      setBounds(0, 0, settings.getValue("width", (long)680).intValue(), settings.getValue("height", (long)480).intValue());
    } catch (Exception ex) {
      setSize(680, 480);
    }
    
    if (value instanceof Variant) {
      Variant v = (Variant)value;
      if (v.getValueType() != VariantType.varBinary) {
        cmViewAsString.performe();
      } else {
        cmViewAsBinary.performe();
      }
    } else if (value instanceof QueryField) {
      cmViewAsJavaObject.performe();
    } else {
      cmViewAsString.performe();
    }
    initServices();
    SwingUtil.centerWithinScreen(this);
  }
  
  private void initServices() {
    ViewValueProvider[] vvp = Application.get().getServiceArray(ViewValueProvider.class);
    if (vvp != null && vvp.length > 0) {
      for (int i=0; i<vvp.length; i++) {
        int vk = menuView.getItemCount() +KeyEvent.VK_1;
        if (vk > KeyEvent.VK_9) {
          vk = i +KeyEvent.VK_A;
        }
        JRadioButtonMenuItem item = new JRadioButtonMenuItem(new ViewValueServiceAction(this, vvp[i], value, vk));
        groupView.add(item);
        menuView.add(item);
      }
    }
  }
  
  public void setCurrentPanel(Component panel) {
    if (currentPanel instanceof Closeable) {
      try {
        ((Closeable)currentPanel).close();
      } catch (IOException ex) {
        ExceptionUtil.processException(ex);
      }
    }
    if (currentPanel != null) {
      getContentPane().remove(currentPanel);
    }
    currentPanel = panel;
    getContentPane().add(panel, BorderLayout.CENTER);
    getContentPane().validate();
  }
  
  @Override
  public void dispose() {
    settings.setValue("width", (long)getWidth());
    settings.setValue("height", (long)getHeight());
    settings.store();
    super.dispose();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmSaveAs = new pl.mpak.sky.gui.swing.Action();
        cmClose = new pl.mpak.sky.gui.swing.Action();
        cmViewAsString = new pl.mpak.sky.gui.swing.Action();
        cmViewAsBinary = new pl.mpak.sky.gui.swing.Action();
        cmViewAsHex = new pl.mpak.sky.gui.swing.Action();
        cmViewAsPicture = new pl.mpak.sky.gui.swing.Action();
        groupView = new javax.swing.ButtonGroup();
        cmViewAsJavaObject = new pl.mpak.sky.gui.swing.Action();
        cmViewHtml = new pl.mpak.sky.gui.swing.Action();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuClose = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuViewAsString = new javax.swing.JRadioButtonMenuItem();
        menuViewAsBinary = new javax.swing.JRadioButtonMenuItem();
        menuViewAsHex = new javax.swing.JRadioButtonMenuItem();
        menuViewAsPicture = new javax.swing.JRadioButtonMenuItem();
        menuViewAsJavaObject = new javax.swing.JRadioButtonMenuItem();
        menuViewHtml = new javax.swing.JRadioButtonMenuItem();

        cmSaveAs.setActionCommandKey("cmSaveAs");
        cmSaveAs.setSmallIcon(pl.mpak.sky.gui.swing.ImageManager.getImage("/pl/mpak/res/icons/save_as16.gif")); // NOI18N
        cmSaveAs.setText(stringManager.getString("cmSaveAs-text")); // NOI18N
        cmSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmSaveAsActionPerformed(evt);
            }
        });

        cmClose.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        cmClose.setText(stringManager.getString("cmClose-text")); // NOI18N
        cmClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmCloseActionPerformed(evt);
            }
        });

        cmViewAsString.setActionCommandKey("cmViewAsString");
        cmViewAsString.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        cmViewAsString.setText(stringManager.getString("ViewValueDialog-cmViewAsString-text")); // NOI18N
        cmViewAsString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewAsStringActionPerformed(evt);
            }
        });

        cmViewAsBinary.setActionCommandKey("vmViewAsBinary");
        cmViewAsBinary.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        cmViewAsBinary.setText(stringManager.getString("ViewValueDialog-cmViewAsBinary-text")); // NOI18N
        cmViewAsBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewAsBinaryActionPerformed(evt);
            }
        });

        cmViewAsHex.setActionCommandKey("cmViewAsHex");
        cmViewAsHex.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        cmViewAsHex.setText(stringManager.getString("ViewValueDialog-cmViewAsHex-text")); // NOI18N
        cmViewAsHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewAsHexActionPerformed(evt);
            }
        });

        cmViewAsPicture.setActionCommandKey("cmViewAsPicture");
        cmViewAsPicture.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        cmViewAsPicture.setText(stringManager.getString("ViewValueDialog-cmViewAsPicture-text")); // NOI18N
        cmViewAsPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewAsPictureActionPerformed(evt);
            }
        });

        cmViewAsJavaObject.setActionCommandKey("cmViewAsJavaObject");
        cmViewAsJavaObject.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        cmViewAsJavaObject.setText(stringManager.getString("ViewValueDialog-cmViewAsJavaObject-text")); // NOI18N
        cmViewAsJavaObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewAsJavaObjectActionPerformed(evt);
            }
        });

        cmViewHtml.setActionCommandKey("cmViewHtml");
        cmViewHtml.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        cmViewHtml.setText(stringManager.getString("ViewValueDialog-cmViewHtml-text")); // NOI18N
        cmViewHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmViewHtmlActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stringManager.getString("ViewValueDialog-title")); // NOI18N
        setModal(true);

        menuFile.setMnemonic('P');
        menuFile.setText(stringManager.getString("ViewValueDialog-menuFile-text")); // NOI18N

        menuSaveAs.setAction(cmSaveAs);
        menuFile.add(menuSaveAs);
        menuFile.add(jSeparator1);

        menuClose.setAction(cmClose);
        menuFile.add(menuClose);

        jMenuBar1.add(menuFile);

        menuView.setMnemonic('W');
        menuView.setText(stringManager.getString("ViewValueDialog-menuView-text")); // NOI18N

        menuViewAsString.setAction(cmViewAsString);
        groupView.add(menuViewAsString);
        menuView.add(menuViewAsString);

        menuViewAsBinary.setAction(cmViewAsBinary);
        groupView.add(menuViewAsBinary);
        menuView.add(menuViewAsBinary);

        menuViewAsHex.setAction(cmViewAsHex);
        groupView.add(menuViewAsHex);
        menuView.add(menuViewAsHex);

        menuViewAsPicture.setAction(cmViewAsPicture);
        groupView.add(menuViewAsPicture);
        menuView.add(menuViewAsPicture);

        menuViewAsJavaObject.setAction(cmViewAsJavaObject);
        groupView.add(menuViewAsJavaObject);
        menuView.add(menuViewAsJavaObject);

        menuViewHtml.setAction(cmViewHtml);
        groupView.add(menuViewHtml);
        menuViewHtml.setSelected(true);
        menuView.add(menuViewHtml);

        jMenuBar1.add(menuView);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmViewAsJavaObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewAsJavaObjectActionPerformed
  menuViewAsJavaObject.setSelected(true);
  if (value instanceof QueryField) {
    setCurrentPanel(new BeanPropertyPanel(value, new String[] {"class", "fieldClass", "metaData", "query", "resultSet"}));
  }
  else {
    setCurrentPanel(new BeanPropertyPanel(value));
  }
}//GEN-LAST:event_cmViewAsJavaObjectActionPerformed

private void cmViewAsPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewAsPictureActionPerformed
  if (value instanceof Variant) {
    menuViewAsPicture.setSelected(true);
    setCurrentPanel(new ViewAsPicturePanel((Variant)value));
  }
}//GEN-LAST:event_cmViewAsPictureActionPerformed
  
private void cmSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmSaveAsActionPerformed
  if (value == null) {
    return;
  }
  File file = FileUtil.selectFileToSave(this, null);
  if (file != null) {
    byte[] buffer = null;
    try  {
      if (value instanceof Variant && ((Variant)value).getValueType() == VariantType.varBinary) {
        buffer = ((Variant)value).getBinary();
      }
      else if (value instanceof Variant) {
        buffer = ((Variant)value).getString().getBytes();
      }
      else {
        buffer = value.toString().getBytes();
      }
      OutputStream stream = new FileOutputStream(file);
      try  {
        stream.write(buffer);
      }
      finally {
        stream.close();
      }
    }
    catch (Exception ex) {
      ExceptionUtil.processException(ex);
      MessageBox.show(this, "B³¹d", ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
    }
  }
}//GEN-LAST:event_cmSaveAsActionPerformed

private void cmViewAsHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewAsHexActionPerformed
  if (value instanceof Variant) {
    menuViewAsHex.setSelected(true);
    setCurrentPanel(new ViewAsHexPanel((Variant)value));
  }
}//GEN-LAST:event_cmViewAsHexActionPerformed

private void cmViewAsBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewAsBinaryActionPerformed
  if (value instanceof Variant) {
    menuViewAsBinary.setSelected(true);
    setCurrentPanel(new ViewAsBinaryPanel((Variant)value));
  }
}//GEN-LAST:event_cmViewAsBinaryActionPerformed

private void cmCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCloseActionPerformed
  dispose();
}//GEN-LAST:event_cmCloseActionPerformed

private void cmViewAsStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewAsStringActionPerformed
  menuViewAsString.setSelected(true);
  setCurrentPanel(new ViewAsStringPanel(value));
}//GEN-LAST:event_cmViewAsStringActionPerformed

private void cmViewHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmViewHtmlActionPerformed
  menuViewHtml.setSelected(true);
  setCurrentPanel(new ViewHtmlPanel(value));
}//GEN-LAST:event_cmViewHtmlActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.mpak.sky.gui.swing.Action cmClose;
    private pl.mpak.sky.gui.swing.Action cmSaveAs;
    private pl.mpak.sky.gui.swing.Action cmViewAsBinary;
    private pl.mpak.sky.gui.swing.Action cmViewAsHex;
    private pl.mpak.sky.gui.swing.Action cmViewAsJavaObject;
    private pl.mpak.sky.gui.swing.Action cmViewAsPicture;
    private pl.mpak.sky.gui.swing.Action cmViewAsString;
    private pl.mpak.sky.gui.swing.Action cmViewHtml;
    private javax.swing.ButtonGroup groupView;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JMenu menuView;
    private javax.swing.JRadioButtonMenuItem menuViewAsBinary;
    private javax.swing.JRadioButtonMenuItem menuViewAsHex;
    private javax.swing.JRadioButtonMenuItem menuViewAsJavaObject;
    private javax.swing.JRadioButtonMenuItem menuViewAsPicture;
    private javax.swing.JRadioButtonMenuItem menuViewAsString;
    private javax.swing.JRadioButtonMenuItem menuViewHtml;
    // End of variables declaration//GEN-END:variables
  
}
