/*
 * ViewAsStringPanel.java
 *
 * Created on 26 listopad 2007, 18:53
 */

package pl.mpak.orbada.jsondataview.gui;

import java.io.Closeable;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import json.JSONArray;
import json.JSONException;
import json.JSONObject;
import pl.mpak.orbada.jsondataview.OrbadaJsonDataViewPlugin;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class ViewJsonDataPanel extends javax.swing.JPanel implements Closeable {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaJsonDataViewPlugin.class);

  private Object value;
  
  /** Creates new form ViewAsStringPanel 
   * @param value 
   */
  public ViewJsonDataPanel(Object value) {
    this.value = value;
    initComponents();
    init();
  }
  
  private void expandObject(DefaultMutableTreeNode aNode, JSONObject object) throws JSONException {
    Iterator<?> i = object.keys();
    while (i.hasNext()) {
      Object key = i.next();
      Object json = object.get(key.toString());
      if (json instanceof JSONObject) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(new ITag(key.toString(), "<object>"));
        expandObject(node, (JSONObject)json);
        aNode.add(node);
      }
      else if (json instanceof JSONArray) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(new ITag(key.toString(), "[array]"));
        expandArray(node, (JSONArray)json);
        aNode.add(node);
      }
      else {
        aNode.add(new DefaultMutableTreeNode(new ITag(key.toString(), json.toString())));
      }
    }
  }
  
  private void expandArray(DefaultMutableTreeNode aNode, JSONArray array) throws JSONException {
    for (int i=0; i<array.length(); i++) {
      Object o = array.get(i);
      if (o instanceof JSONObject) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(new ITag("(noname)", "<object>"));
        expandObject(node, (JSONObject)o);
        aNode.add(node);
      }
      else if (o instanceof JSONArray) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(new ITag("(noname)", "[array]"));
        expandArray(node, (JSONArray)o);
        aNode.add(node);
      }
      else {
        aNode.add(new DefaultMutableTreeNode(new ITag(o.toString())));
      }
    }
  }

  private TreeModel parse(String source) throws Exception {
    source = source.trim();
    DefaultMutableTreeNode root = null;
    if (source.length() >= 2 && source.charAt(0) == '[' && source.charAt(source.length() -1) == ']') {
      root = new DefaultMutableTreeNode(new ITag("root", "[array]"));
      JSONArray array = new JSONArray(source);
      expandArray(root, array);
    }
    else {
      root = new DefaultMutableTreeNode(new ITag("root", "<object>"));
      JSONObject object = new JSONObject(source);
      expandObject(root, object);
    }
    return new DefaultTreeModel(root);
  }

  private void init() {
    if (value != null) {
      try {
        treeXml.setModel(parse(value.toString()));
      } catch (Exception ex) {
        MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      }
    }
  }
  
  public void close() throws IOException {
    
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeXml = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        treeXml.setModel(null);
        jScrollPane1.setViewportView(treeXml);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeXml;
    // End of variables declaration//GEN-END:variables
  
}
