package pl.mpak.orbada.mysql.gui.wizards;

import pl.mpak.orbada.mysql.OrbadaMySQLPlugin;
import pl.mpak.orbada.mysql.gui.util.DatabaseComboBoxModel;
import pl.mpak.orbada.mysql.gui.util.EngineComboBoxModel;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.StringUtil;

/**
 *
 * @author  akaluza
 */
public class CopyAsTableWizard extends SqlCodeWizardPanel {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager("mysql");

  private Database database;
  private String databaseName;
  private String tableName;
  private String engine;
  
  public CopyAsTableWizard(Database database, String databaseName, String tableName, String engine) {
    this.database = database;
    this.databaseName = databaseName;
    this.tableName = tableName;
    this.engine = engine;
    initComponents();
    init();
  }
  
  private void init() {
    textTableName.setText(SQLUtil.createSqlName(databaseName, tableName, database));
    comboDatabases.setModel(new DatabaseComboBoxModel(database));
    comboEngine.setModel(new EngineComboBoxModel(database));
  }
  
  public void wizardShow() {
    ((DatabaseComboBoxModel)comboDatabases.getModel()).change();
    ((DatabaseComboBoxModel)comboDatabases.getModel()).select(databaseName, comboDatabases);
    ((EngineComboBoxModel)comboEngine.getModel()).change();
    ((EngineComboBoxModel)comboEngine.getModel()).select(StringUtil.nvl(engine, "MyISAM"), comboEngine);
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        textNewTableName.requestFocusInWindow();
      }
    });
  }
  
  public String getDialogTitle() {
    return stringManager.getString("CopyAsTableWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("CopyAsTableWizard-tab-title");
  }
  
  public String getSqlCode() {
    String newTableName = textNewTableName.getText();
    if ("".equals(newTableName)) {
      newTableName = this.tableName +"_" +String.format("%1$tY%1$tm%1$td%1$tH%1$tM%1$tS", new Object[] {System.currentTimeMillis()});
    }
    getResultMap().put("new-table-name", newTableName);
    return
      "CREATE TABLE " +SQLUtil.createSqlName(comboDatabases.getSelectedItem().toString(), database) +"." +newTableName +
      " ENGINE=" +comboEngine.getText() +
      " AS\n" +
      "SELECT * FROM " +SQLUtil.createSqlName(databaseName, this.tableName, database) +
      (!checkData.isSelected() ? "\n WHERE 1 = 0" : "");
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    textNewTableName = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel6 = new javax.swing.JLabel();
    checkData = new javax.swing.JCheckBox();
    jLabel2 = new javax.swing.JLabel();
    textTableName = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel7 = new javax.swing.JLabel();
    comboDatabases = new pl.mpak.sky.gui.swing.comp.ComboBox();
    comboEngine = new pl.mpak.sky.gui.swing.comp.ComboBox();

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText(stringManager.getString("new-table-name-dd")); // NOI18N

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText(stringManager.getString("new-table-database-dd")); // NOI18N

    checkData.setSelected(true);
    checkData.setText(stringManager.getString("copy-data-also")); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("table-name-dd")); // NOI18N

    textTableName.setEditable(false);
    textTableName.setFocusable(false);

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText(stringManager.getString("table-engine-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textTableName, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboDatabases, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboEngine, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkData)
              .addComponent(textNewTableName, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(textTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(comboDatabases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(comboEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(textNewTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkData)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkData;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboDatabases;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboEngine;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private pl.mpak.sky.gui.swing.comp.TextField textNewTableName;
  private pl.mpak.sky.gui.swing.comp.TextField textTableName;
  // End of variables declaration//GEN-END:variables
  
}
