/*
 * ExplainPlanPanel.java
 *
 * Created on 30 grudzieñ 2007, 16:41
 */

package pl.mpak.orbada.jaybird.gui;

import java.io.Closeable;
import java.io.IOException;
import java.lang.reflect.Method;
import java.sql.Statement;
import pl.mpak.orbada.jaybird.OrbadaJaybirdPlugin;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class ExplainPlanPanel extends javax.swing.JPanel implements Closeable {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager("jaybird");
  private Database database;
  
  /** Creates new form ExplainPlanPanel */
  public ExplainPlanPanel(Database database) {
    this.database = database;
    initComponents();
    init();
  }
  
  private void init() {
  }
  
  public void close() throws IOException {
  }
  
  public void updatePlan(String sqlText) {
    try {
      Query query = database.createQuery();
      query.setSqlText(sqlText);
      Statement statement = database.getConnection().prepareStatement(query.getPreparedSqlText());
      try {
        Method method = statement.getClass().getMethod("getExecutionPlan", (Class<?>[])null);
        if (method == null) {
          textPlan.setText(stringManager.getString("ExplainPlanPanel.no_get_execution_plan_message"));
        }
        else {
          textPlan.setText((String)method.invoke(statement, (Object[])null));
        }
      } finally {
        statement.close();
      }
    } catch (Throwable ex) {
      ExceptionUtil.processException(ex);
      textPlan.setText(ex.getClass().getName() +"\n" +ex.getMessage());
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    textPlan = new pl.mpak.sky.gui.swing.comp.TextArea();

    setLayout(new java.awt.BorderLayout());

    textPlan.setColumns(20);
    textPlan.setRows(5);
    textPlan.setFont(new java.awt.Font("Courier New", 0, 12));
    jScrollPane1.setViewportView(textPlan);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private pl.mpak.sky.gui.swing.comp.TextArea textPlan;
  // End of variables declaration//GEN-END:variables
  
}
