/*
 * GeneralSettingsProvider.java
 *
 * Created on 10 grudzieñ 2007, 20:05
 */

package pl.mpak.orbada.jaybird.gui;

import pl.mpak.orbada.jaybird.OrbadaJaybirdPlugin;
import pl.mpak.orbada.jaybird.services.JaybirdGeneralSettingsService;
import pl.mpak.orbada.plugins.IApplication;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.plugins.ISettingsComponent;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class GeneralSettingsPanel extends javax.swing.JPanel implements ISettingsComponent {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager(OrbadaJaybirdPlugin.class);
  private IApplication application;
  private ISettings settings;
  
  /** Creates new form GeneralSettingsProvider */
  public GeneralSettingsPanel(IApplication application) {
    this.application = application;
    initComponents();
    init();
  }
  
  private void init() {
    settings = application.getSettings(JaybirdGeneralSettingsService.settingsName);
    restoreSettings();
  }
  
  public void restoreSettings() {
    checkMultiExplainPlan.setSelected(settings.getValue(JaybirdGeneralSettingsService.SET_MultiExplainPlan, false));
  }

  public void applySettings() {
    settings.setValue(JaybirdGeneralSettingsService.SET_MultiExplainPlan, checkMultiExplainPlan.isSelected());
    settings.store();
  }

  public void cancelSettings() {
    restoreSettings();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    checkMultiExplainPlan = new javax.swing.JCheckBox();

    checkMultiExplainPlan.setText(stringManager.getString("checkMultiExplainPlan.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkMultiExplainPlan)
        .addContainerGap(150, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkMultiExplainPlan)
        .addContainerGap(293, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkMultiExplainPlan;
  // End of variables declaration//GEN-END:variables
  
}
