/*
 * CreateIndexWizardPanel.java
 *
 * Created on 22 listopad 2007, 22:42
 */

package pl.mpak.orbada.hsqldb.gui.wizards;

import java.util.ArrayList;
import pl.mpak.orbada.hsqldb.OrbadaHSqlDbPlugin;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.orbada.universal.gui.util.SchemaComboBoxModel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class RevokeClassWizardPanel extends SqlCodeWizardPanel {
  
  private StringManager stringManager = StringManagerFactory.getStringManager("hsqldb");

  private Database database;
  private String schemaName;
  
  /** Creates new form CreateIndexWizardPanel
   * @param database
   * @param schemaName
   */
  public RevokeClassWizardPanel(Database database, String schemaName) {
    this.database = database;
    this.schemaName = schemaName;
    initComponents();
    init();
  }
  
  private void init() {
    Query query = database.createQuery();
    try {
      ArrayList<String> list = new ArrayList<String>();
      query.setSqlText(
        "select distinct procedure_name object_name from information_schema.SYSTEM_PROCEDURES\n" +
        " where origin <> 'ALIAS'\n" +
        "   and procedure_schem = :SCHEMA_NAME\n" +
        "union\n" +
        "select distinct object_name from information_schema.SYSTEM_ALIASES\n" +
        " where object_type = 'ROUTINE'\n" +
        "   and object_schem = :SCHEMA_NAME\n" +
        " order by object_name");
      query.paramByName("schema_name").setString(schemaName);
      query.open();
      while (!query.eof()) {
        String clazz = query.fieldByName("object_name").getString();
        clazz = clazz.substring(0, clazz.lastIndexOf('.'));
        if (list.indexOf(clazz) == -1) {
          list.add(clazz);
        }
        query.next();
      }
      for (String item : list) {
        comboClass.addItem(item);
      }
    }
    catch (Exception ex) {
      ExceptionUtil.processException(ex);
    }
    finally {
      query.close();
    }
    comboSchemas.setModel(new SchemaComboBoxModel(database));
  }
  
  public void wizardShow() {
    ((SchemaComboBoxModel)comboSchemas.getModel()).change();
    ((SchemaComboBoxModel)comboSchemas.getModel()).select(schemaName, comboSchemas);
  }
  
  public String getDialogTitle() {
    return stringManager.getString("RevokeClassWizardPanel-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("RevokeClassWizardPanel-tab-title");
  }
  
  public String getSqlCode() {
    return 
      "REVOKE ALL ON CLASS \"" +comboClass.getSelectedItem().toString() +"\" FROM " +
      SQLUtil.createSqlName(comboSchemas.getSelectedItem().toString());
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    comboClass = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    comboSchemas = new javax.swing.JComboBox();

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText(stringManager.getString("class-dd")); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("schema-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboClass, 0, 246, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboSchemas, 0, 246, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(comboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(comboSchemas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox comboClass;
  private javax.swing.JComboBox comboSchemas;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
  
}
