/*
 * DiffViewPanel.java
 *
 * Created on 28 listopad 2008, 11:56
 */

package pl.mpak.orbada.melddiff.gui;

import java.io.Closeable;
import java.io.IOException;
import org.jmeld.ui.JMeldPanel;
import pl.mpak.orbada.plugins.IViewAccesibilities;

/**
 *
 * @author  akaluza
 */
public class DiffViewPanel extends javax.swing.JPanel implements Closeable {

  private IViewAccesibilities accesibilities;
  private boolean viewClosing = false;
  private JMeldPanel meldPanel;
  
  /** Creates new form DiffViewPanel */
  public DiffViewPanel(IViewAccesibilities accesibilities) {
    this.accesibilities = accesibilities;
    initComponents();
    init();
  }
  
  private void init() {
    meldPanel = new JMeldPanel();
    add(meldPanel);
  }

  public void close() throws IOException {
    viewClosing = true;
    accesibilities = null;
  }

  public JMeldPanel getMeldPanel() {
    return meldPanel;
  }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
