/*
 * ErrorBox.java
 *
 * Created on 6 listopad 2007, 20:06
 */

package pl.mpak.orbada.universal.gui;

import javax.swing.JComponent;
import pl.mpak.orbada.gui.webapp.RequestErrorDialog;
import pl.mpak.orbada.universal.OrbadaUniversalPlugin;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class ErrorBox extends javax.swing.JDialog {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaUniversalPlugin.class);

  private Throwable exception;
  private String extInfo;
  
  /** Creates new form ErrorBox 
   * @param exception 
   */
  public ErrorBox(Throwable exception) {
    this(exception, null);
  }

  public ErrorBox(Throwable exception, String extInfo) {
    super();
    this.exception = exception;
    initComponents();
    init();
  }
  
  public static void show(Throwable exception) {
    ErrorBox dialog = new ErrorBox(exception);
    dialog.setVisible(true);
  }
  
  public static void show(Throwable exception, String extInfo) {
    ErrorBox dialog = new ErrorBox(exception, extInfo);
    dialog.setVisible(true);
  }

  private void init() {
    //buttonErrorRequest.setVisible(false);
    
    SwingUtil.centerWithinScreen(this);
    textMessage.setText("");
    if (extInfo != null) {
      textMessage.append(extInfo +"\n");
    }
    textMessage.append(exception.getMessage());
    textMessage.setCaretPosition(0);
    textStackTrace.setText(ExceptionUtil.getStackTrace(exception));
    textStackTrace.setCaretPosition(0);
    
    getRootPane().setDefaultButton(buttonClose);
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmClose.getShortCut(), "cmClose");
    getRootPane().getActionMap().put("cmClose", cmClose);
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        buttonClose.requestFocusInWindow();
      }
    });
  }
    
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmClose = new pl.mpak.sky.gui.swing.Action();
    cmErrorRequest = new pl.mpak.sky.gui.swing.Action();
    buttonClose = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    textMessage = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    textStackTrace = new javax.swing.JTextArea();
    buttonErrorRequest = new javax.swing.JButton();

    cmClose.setActionCommandKey("cmClose");
    cmClose.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmClose.setText(stringManager.getString("cmClose-text")); // NOI18N
    cmClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCloseActionPerformed(evt);
      }
    });

    cmErrorRequest.setActionCommandKey("cmErrorRequest");
    cmErrorRequest.setText(stringManager.getString("cmErrorRequest-text")); // NOI18N
    cmErrorRequest.setTooltip(stringManager.getString("cmErrorRequest-hint")); // NOI18N
    cmErrorRequest.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmErrorRequestActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("B³¹d");
    setModal(true);

    buttonClose.setAction(cmClose);
    buttonClose.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonClose.setPreferredSize(new java.awt.Dimension(75, 23));

    textMessage.setColumns(20);
    textMessage.setFont(new java.awt.Font("Courier New", 0, 11));
    textMessage.setRows(5);
    jScrollPane1.setViewportView(textMessage);

    textStackTrace.setColumns(20);
    textStackTrace.setFont(new java.awt.Font("Courier New", 0, 11));
    textStackTrace.setRows(5);
    jScrollPane2.setViewportView(textStackTrace);

    buttonErrorRequest.setAction(cmErrorRequest);
    buttonErrorRequest.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonErrorRequest.setPreferredSize(new java.awt.Dimension(75, 23));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(buttonErrorRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 500, Short.MAX_VALUE)
            .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonErrorRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void cmCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCloseActionPerformed
  dispose();
}//GEN-LAST:event_cmCloseActionPerformed

private void cmErrorRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmErrorRequestActionPerformed
  RequestErrorDialog.showDialog(exception);
}//GEN-LAST:event_cmErrorRequestActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonClose;
  private javax.swing.JButton buttonErrorRequest;
  private pl.mpak.sky.gui.swing.Action cmClose;
  private pl.mpak.sky.gui.swing.Action cmErrorRequest;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea textMessage;
  private javax.swing.JTextArea textStackTrace;
  // End of variables declaration//GEN-END:variables
  
}
