/*
 * SelectDatabaseDialog.java
 *
 * Created on 2 listopad 2007, 18:02
 */

package pl.mpak.orbada.universal.gui;

import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import pl.mpak.orbada.core.Application;
import pl.mpak.orbada.db.InternalDatabase;
import pl.mpak.orbada.universal.OrbadaUniversalPlugin;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.DatabaseManager;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class SelectDatabaseDialog extends javax.swing.JDialog {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager("universal");

  private int modalResult = ModalResult.NONE;
  private Database database;
  private boolean constraintType;

  /** 
   * Creates new form SelectDatabaseDialog 
   * @param database 
   * @param constraintType 
   */
  public SelectDatabaseDialog(Database database, boolean constraintType) {
    super(SwingUtil.getRootFrame());
    this.database = database;
    this.constraintType = constraintType;
    initComponents();
    init();
  }
  
  public static Database show(Database database, boolean constraintType) {
    SelectDatabaseDialog dialog = new SelectDatabaseDialog(database, constraintType);
    dialog.setVisible(true);
    if (dialog.modalResult == ModalResult.OK) {
      return (Database)dialog.listDatabases.getSelectedValue();
    }
    return null;
  }
  
  private void init() {
    SwingUtil.centerWithinScreen(this);
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmCancel.getShortCut(), "cmCancel");
    getRootPane().getActionMap().put("cmCancel", cmCancel);
    getRootPane().setDefaultButton(buttonOk);
    
    listDatabases.setCellRenderer(new DefaultListCellRenderer() {
      public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel label = (JLabel)super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value != null) {
          Database database = (Database)value;
          String text = "<html>";
          if (database.getPublicName() == null) {
            text = text +"<b>" +database.getUserName() +"</b>";
          } else {
            text = text +"<b>" +database.getPublicName() +"</b> as " +database.getUserName();
          }
          text = text +"<br>" +database.getUrl();
          label.setText(text);
          label.setVerticalAlignment(JLabel.TOP);
        }
        return label;
      }
    });
    
    listDatabases.removeAll();
    listDatabases.setModel(new DefaultListModel());
    for (int i=0; i<DatabaseManager.getManager().getDatabaseCount(); i++) {
      if (!constraintType || DatabaseManager.getManager().getDatabase(i).getDriverType().equals(database.getDriverType())) {
        if (!DatabaseManager.getManager().getDatabase(i).equals(InternalDatabase.get()) || Application.get().isUserAdmin()) {
          ((DefaultListModel)listDatabases.getModel()).addElement(DatabaseManager.getManager().getDatabase(i));
        }
      }
    }
    listDatabases.setSelectedValue(database, true);
    
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        listDatabases.requestFocus();
      }
    });
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmCancel = new pl.mpak.sky.gui.swing.Action();
    cmSelect = new pl.mpak.sky.gui.swing.Action();
    jScrollPane1 = new javax.swing.JScrollPane();
    listDatabases = new javax.swing.JList();
    buttonCancel = new javax.swing.JButton();
    buttonOk = new javax.swing.JButton();

    cmCancel.setActionCommandKey("cmCancel");
    cmCancel.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmCancel.setText(stringManager.getString("cmCancel-text")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    cmSelect.setActionCommandKey("cmSelect");
    cmSelect.setText(stringManager.getString("cmSelect-text")); // NOI18N
    cmSelect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmSelectActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("SelectDatabaseDialog-title")); // NOI18N
    setModal(true);

    listDatabases.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    listDatabases.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listDatabasesValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(listDatabases);

    buttonCancel.setAction(cmCancel);
    buttonCancel.setPreferredSize(new java.awt.Dimension(75, 23));

    buttonOk.setAction(cmSelect);
    buttonOk.setPreferredSize(new java.awt.Dimension(75, 23));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void listDatabasesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDatabasesValueChanged
  cmSelect.setEnabled(listDatabases.getSelectedIndex() != -1);
}//GEN-LAST:event_listDatabasesValueChanged

private void cmSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmSelectActionPerformed
  modalResult = ModalResult.OK;
  dispose();
}//GEN-LAST:event_cmSelectActionPerformed

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  modalResult = ModalResult.CANCEL;
  dispose();
}//GEN-LAST:event_cmCancelActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private pl.mpak.sky.gui.swing.Action cmSelect;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList listDatabases;
  // End of variables declaration//GEN-END:variables
  
}
