/*
 * PragmaCacheSizeWizard.java
 *
 * Created on 2011-05-01, 15:58:21
 */

package pl.mpak.orbada.sqlite.gui.wizards;

import pl.mpak.orbada.sqlite.OrbadaSQLitePlugin;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author akaluza
 */
public class PragmaCacheSizeWizard extends SqlCodeWizardPanel {

  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaSQLitePlugin.class);

  private Database database;
  private String databaseName;

  public PragmaCacheSizeWizard(Database database, String databaseName) {
    this.database = database;
    this.databaseName = databaseName;
    initComponents();
    init();
  }

  private void init() {
  }

  public void wizardShow() {
    try {
      Query query = database.createQuery("PRAGMA " +(databaseName != null ? SQLUtil.createSqlName(databaseName, database) +"." : "") +"CACHE_SIZE");
      try {
        textCacheSize.setText(query.fieldByName("cache_size").getString());
      }
      finally {
        query.close();
      }
    } catch (Exception ex) {
    }
  }

  public String getDialogTitle() {
    return stringManager.getString("cache-size");
  }

  public String getTabTitle() {
    return stringManager.getString("size");
  }

  public String getSqlCode() {
    return "PRAGMA " +(databaseName != null ? SQLUtil.createSqlName(databaseName, database) +"." : "") +"CACHE_SIZE = " +textCacheSize.getText();
  }

  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    textCacheSize = new pl.mpak.sky.gui.swing.comp.ComboBox();

    jLabel1.setText(stringManager.getString("cache-size-dd")); // NOI18N

    textCacheSize.setEditable(true);
    textCacheSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "4000", "8000", "16000" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textCacheSize, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(111, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(textCacheSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(41, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private pl.mpak.sky.gui.swing.comp.ComboBox textCacheSize;
  // End of variables declaration//GEN-END:variables

}
