package pl.mpak.orbada.derbydb.views;

import java.awt.Frame;
import java.io.IOException;

import pl.mpak.orbada.gui.comps.OrbadaSyntaxTextArea;
import pl.mpak.orbada.derbydb.DerbyDbSql;
import pl.mpak.orbada.derbydb.OrbadaDerbyDbPlugin;
import pl.mpak.orbada.gui.ITabObjectInfo;
import pl.mpak.orbada.gui.cm.ComponentActionsAction;
import pl.mpak.orbada.plugins.IViewAccesibilities;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.timer.Timer;

/**
 *
 * @author  akaluza
 */
public class ViewSourcePanel extends javax.swing.JPanel implements ITabObjectInfo {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager(OrbadaDerbyDbPlugin.class);

  private IViewAccesibilities accesibilities;
  private String currentSchemaName = "";
  private String currentViewName = "";
  private boolean requestRefresh = false;
  
  private Timer timer;
  
  /** Creates new form ViewSourcePanel
   * @param accesibilities
   */
  public ViewSourcePanel(IViewAccesibilities accesibilities) {
    this.accesibilities = accesibilities;
    initComponents();
    init();
  }
  
  private void setEditorText(final String text) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        syntaxViewSource.setText(text);
      }
    });
  }
  
  private void init() {
    timer = new Timer(250) {
      {
        setEnabled(false);
      }
      public void run() {
        setEnabled(false);
        requestRefresh = false;
        Query query = getDatabase().createQuery();
        try {
          query.setSqlText(DerbyDbSql.getViewSource());
          query.paramByName("schemaname").setString(currentSchemaName);
          query.paramByName("viewname").setString(currentViewName);
          query.open();
          if (!query.eof()) {
            setEditorText("drop view \"" +currentSchemaName +"\".\"" +currentViewName +"\"\n/\n" +query.fieldByName("viewdefinition").getString() +"\n/");
          } else {
            setEditorText("");
          }
          syntaxViewSource.getStatusBar().getPanel("view-status").setText(" ");
        } catch (Exception ex) {
          ExceptionUtil.processException(ex);
        } finally {
          query.close();
        }
      }
    };
    SwingUtil.addAction(syntaxViewSource.getEditorArea(), cmCompile);
    syntaxViewSource.getStatusBar().addPanel("view-status").setText(" ");
    syntaxViewSource.setDatabase(getDatabase());
    OrbadaDerbyDbPlugin.getRefreshQueue().add(timer);
    new ComponentActionsAction(getDatabase(), syntaxViewSource.getEditorArea(), buttonActions, menuActions, "derbydb-view-source-actions");
  }
  
  public Database getDatabase() {
    return accesibilities.getDatabase();
  }
  
  public String getTitle() {
    return stringManager.getString("ViewSourcePanel-title");
  }
  
  public void refresh() {
    refresh(null, currentSchemaName, currentViewName);
  }
  
  public void refresh(String catalogName, String schemaName, String objectName) {
    if (!currentSchemaName.equals(schemaName) || !currentViewName.equals(objectName) || requestRefresh) {
      currentSchemaName = schemaName;
      currentViewName = objectName;
      if (isVisible()) {
        timer.restart();
      } else {
        requestRefresh = true;
        setEditorText("");
      }
    }
  }
  
  @Override
  public boolean canClose() {
    return true;
  }

  public void close() throws IOException {
    timer.cancel();
    syntaxViewSource.setDatabase(null);
    accesibilities = null;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmRefresh = new pl.mpak.sky.gui.swing.Action();
    cmCompile = new pl.mpak.sky.gui.swing.Action();
    menuActions = new javax.swing.JPopupMenu();
    toolBarContent = new javax.swing.JToolBar();
    buttonRefresh = new pl.mpak.sky.gui.swing.comp.ToolButton();
    buttonCompile = new pl.mpak.sky.gui.swing.comp.ToolButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    buttonActions = new pl.mpak.sky.gui.swing.comp.ToolButton();
    syntaxViewSource = new OrbadaSyntaxTextArea();

    cmRefresh.setSmallIcon(pl.mpak.sky.gui.swing.ImageManager.getImage("/pl/mpak/res/icons/refresh16.gif")); // NOI18N
    cmRefresh.setText(stringManager.getString("cmRefresh-text")); // NOI18N
    cmRefresh.setTooltip(stringManager.getString("ViewSourcePanel-cmRefresh-hint")); // NOI18N
    cmRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmRefreshActionPerformed(evt);
      }
    });

    cmCompile.setActionCommandKey("cmCompile");
    cmCompile.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
    cmCompile.setSmallIcon(pl.mpak.sky.gui.swing.ImageManager.getImage("/pl/mpak/res/icons/execute_script16.gif")); // NOI18N
    cmCompile.setText(stringManager.getString("ViewSourcePanel-cmCompile-text")); // NOI18N
    cmCompile.setTooltip(stringManager.getString("ViewSourcePanel-cmCompile-hint")); // NOI18N
    cmCompile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCompileActionPerformed(evt);
      }
    });

    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
      }
    });
    setLayout(new java.awt.BorderLayout());

    toolBarContent.setFloatable(false);
    toolBarContent.setRollover(true);

    buttonRefresh.setAction(cmRefresh);
    buttonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    buttonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    toolBarContent.add(buttonRefresh);

    buttonCompile.setAction(cmCompile);
    buttonCompile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    buttonCompile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    toolBarContent.add(buttonCompile);
    toolBarContent.add(jSeparator1);

    buttonActions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    buttonActions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    toolBarContent.add(buttonActions);

    add(toolBarContent, java.awt.BorderLayout.PAGE_START);
    add(syntaxViewSource, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  
private void cmCompileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCompileActionPerformed
  if (MessageBox.show((Frame)null, stringManager.getString("ViewSourcePanel-script"), stringManager.getString("ViewSourcePanel-execute-script-q"), ModalResult.YESNO) != ModalResult.YES) {
    return;
  }
  
  try {
    getDatabase().executeScript(syntaxViewSource.getText());
    syntaxViewSource.getStatusBar().getPanel("view-status").setText(stringManager.getString("ViewSourcePanel-exec-properly"));
  } catch (Exception ex) {
    ExceptionUtil.processException(ex);
    syntaxViewSource.getStatusBar().getPanel("view-status").setText(ex.getMessage());
  }
}//GEN-LAST:event_cmCompileActionPerformed

private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
  refresh(null, currentSchemaName, currentViewName);
}//GEN-LAST:event_formComponentShown

private void cmRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmRefreshActionPerformed
  timer.restart();
}//GEN-LAST:event_cmRefreshActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.comp.ToolButton buttonActions;
  private pl.mpak.sky.gui.swing.comp.ToolButton buttonCompile;
  private pl.mpak.sky.gui.swing.comp.ToolButton buttonRefresh;
  private pl.mpak.sky.gui.swing.Action cmCompile;
  private pl.mpak.sky.gui.swing.Action cmRefresh;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JPopupMenu menuActions;
  private OrbadaSyntaxTextArea syntaxViewSource;
  private javax.swing.JToolBar toolBarContent;
  // End of variables declaration//GEN-END:variables
  
}
