package pl.mpak.orbada.oracle.gui.settings;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.oracle.services.OracleSettingsProvider;
import pl.mpak.orbada.plugins.IApplication;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.plugins.ISettingsComponent;
import pl.mpak.usedb.core.Database;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class OracleConnectionSettingsPanel extends javax.swing.JPanel implements ISettingsComponent {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOraclePlugin.class);

  private IApplication application;
  private ISettings settings;
  private Database database;

  public OracleConnectionSettingsPanel(IApplication application, Database database) {
    this.application = application;
    this.database = database;
    initComponents();
    init();
  }
  
  private void init() {
    settings = application.getSettings(database.getUserProperties().getProperty("schemaId"), OracleSettingsProvider.settingsName);
    restoreSettings();
  }
  
  public void restoreSettings() {
    checkUseGlobalSettings.setSelected(settings.getValue(OracleSettingsProvider.setUseGlobalSettings, true));
    checkEditorHighlightSynonyms.setSelected(settings.getValue(OracleSettingsProvider.setEditorHighlightSynonyms, false));
    checkResolveTableMetadataProblem.setSelected(settings.getValue(OracleSettingsProvider.setSolveTableMetadataProblem, false));
    enableControls();
  }

  public void applySettings() {
    settings.setValue(OracleSettingsProvider.setUseGlobalSettings, checkUseGlobalSettings.isSelected());
    settings.setValue(OracleSettingsProvider.setEditorHighlightSynonyms, checkEditorHighlightSynonyms.isSelected());
    settings.setValue(OracleSettingsProvider.setSolveTableMetadataProblem, checkResolveTableMetadataProblem.isSelected());
    settings.store();
  }

  public void cancelSettings() {
    restoreSettings();
  }

  private void enableControls() {
    checkEditorHighlightSynonyms.setEnabled(!checkUseGlobalSettings.isSelected());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkEditorHighlightSynonyms = new javax.swing.JCheckBox();
        checkUseGlobalSettings = new javax.swing.JCheckBox();
        checkResolveTableMetadataProblem = new javax.swing.JCheckBox();

        checkEditorHighlightSynonyms.setText(stringManager.getString("checkEditorHighlightSynonyms-text")); // NOI18N

        checkUseGlobalSettings.setText(stringManager.getString("checkUseGlobalSettings-text")); // NOI18N
        checkUseGlobalSettings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkUseGlobalSettingsItemStateChanged(evt);
            }
        });

        checkResolveTableMetadataProblem.setText(stringManager.getString("checkSolveTableMetadataProblem-text")); // NOI18N
        checkResolveTableMetadataProblem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkResolveTableMetadataProblemItemStateChanged(evt);
            }
        });
        checkResolveTableMetadataProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkResolveTableMetadataProblemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkUseGlobalSettings)
                    .addComponent(checkEditorHighlightSynonyms)
                    .addComponent(checkResolveTableMetadataProblem))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkUseGlobalSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkEditorHighlightSynonyms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkResolveTableMetadataProblem)
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void checkUseGlobalSettingsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkUseGlobalSettingsItemStateChanged
    enableControls();
}//GEN-LAST:event_checkUseGlobalSettingsItemStateChanged

  private void checkResolveTableMetadataProblemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkResolveTableMetadataProblemItemStateChanged
    // TODO add your handling code here:
  }//GEN-LAST:event_checkResolveTableMetadataProblemItemStateChanged

  private void checkResolveTableMetadataProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkResolveTableMetadataProblemActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_checkResolveTableMetadataProblemActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkEditorHighlightSynonyms;
    private javax.swing.JCheckBox checkResolveTableMetadataProblem;
    private javax.swing.JCheckBox checkUseGlobalSettings;
    // End of variables declaration//GEN-END:variables
  
}
