/*
 * QueryHistoryPanel.java
 *
 * Created on 21 paüdziernik 2007, 10:57
 */

package pl.mpak.orbada.universal.gui.history;

import java.io.Closeable;
import java.io.IOException;

import pl.mpak.orbada.gui.comps.table.Table;
import pl.mpak.usedb.core.Command;
import pl.mpak.usedb.core.Query;

/**
 *
 * @author  akaluza
 */
public class QueryHistoryPanel extends javax.swing.JPanel implements Closeable {
  
  private QueryHistory history;
  private QueryHistoryTableModel historyTableModel;
  
  /** Creates new form QueryHistoryPanel */
  public QueryHistoryPanel() {
    initComponents();
    init();
  }
  
  private void init() {
    history = new QueryHistory();
    historyTableModel = new QueryHistoryTableModel(history);
    tableHistory.setModel(historyTableModel);
    historyTableModel.configureTable(tableHistory);
  }
  
  public QueryHistory getHistory() {
    return history;
  }
  
  private void refreshTable() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        tableHistory.revalidate();
        tableHistory.repaint();
      }
    });
  }
  
  public QueryHistoryItem add(Query query) {
    QueryHistoryItem item = history.add(query);
    refreshTable();
    return item;
  }

  public QueryHistoryItem add(Command command) {
    QueryHistoryItem item = history.add(command);
    refreshTable();
    return item;
  }

  public void close() throws IOException {
    if (history != null) {
      history.clear();
      history = null;
    }
    historyTableModel = null;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tableHistory = new Table();

    setLayout(new java.awt.BorderLayout());

    jScrollPane1.setViewportView(tableHistory);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private Table tableHistory;
  // End of variables declaration//GEN-END:variables

}
