/*
 * TaskPanel.java
 *
 * Created on 12 listopad 2007, 18:30
 */

package pl.mpak.orbada.system.gui;

import pl.mpak.orbada.system.OrbadaSystemPlugin;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.task.Task;
import pl.mpak.util.timer.Timer;
import pl.mpak.util.timer.TimerManager;

/**
 *
 * @author  akaluza
 */
public class TaskPanel extends javax.swing.JPanel {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager(OrbadaSystemPlugin.class);
  private Task task;
  private Timer timer;
  
  /** 
   * Creates new form TaskPanel 
   * @param task 
   */
  public TaskPanel(Task task) {
    this.task = task;
    initComponents();
    init();
  }
  
  private void init() {
    timer = new Timer(10) {
      public void run() {
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
            labelTaskDescription.setText(task.getDescription());
            progressTask.setValue(task.getPercenExecution());
            updateStatus();
          }
        });
      }
    };
    labelThreadName.setText(task.getTaskPool().getName());
    labelTaskDescription.setText(task.getDescription());
    progressTask.setMinimum(0);
    progressTask.setMaximum(100);
    progressTask.setValue(task.getPercenExecution());
    setFocusable(true);
    updateStatus();
    TimerManager.getGlobal().add(timer);
  }
  
  public void updateStatus() {
    if (task.isExecuting()) {
      labelStatus.setText(stringManager.getString("executing"));
    }
    else if (task.isCanceled()) {
      labelStatus.setText(stringManager.getString("canceling"));
      cmCancel.setEnabled(false);
    }
    else {
      labelStatus.setText(stringManager.getString("waiting"));
    }
  }
  
  public void close() {
    timer.cancel();
  }
  
  public Task getTask() {
    return task;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmCancel = new pl.mpak.sky.gui.swing.Action();
    labelThreadName = new javax.swing.JLabel();
    labelTaskDescription = new javax.swing.JLabel();
    progressTask = new javax.swing.JProgressBar();
    jButton1 = new javax.swing.JButton();
    labelStatus = new javax.swing.JLabel();

    cmCancel.setActionCommandKey("cmCancel");
    cmCancel.setSmallIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/stop10.gif"))); // NOI18N
    cmCancel.setText(stringManager.getString("cancel")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, javax.swing.UIManager.getDefaults().getColor("controlShadow")));

    labelThreadName.setText("labelThreadName");

    labelTaskDescription.setText("labelTaskDescription");

    jButton1.setAction(cmCancel);
    jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jButton1.setPreferredSize(new java.awt.Dimension(60, 20));

    labelStatus.setText("jLabel1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelThreadName, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(labelTaskDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
              .addComponent(progressTask, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelThreadName)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelTaskDescription)
          .addComponent(labelStatus))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(progressTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  task.setCanceled(true);
  updateStatus();
}//GEN-LAST:event_cmCancelActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel labelStatus;
  private javax.swing.JLabel labelTaskDescription;
  private javax.swing.JLabel labelThreadName;
  private javax.swing.JProgressBar progressTask;
  // End of variables declaration//GEN-END:variables
  
}
