package pl.mpak.orbada.gui;

import java.awt.Component;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JTabbedPane;

import pl.mpak.orbada.Consts;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class SelectTabDialog extends javax.swing.JDialog {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager("orbada");

  private int modalResult = ModalResult.NONE;
  private JTabbedPane pane;

  public SelectTabDialog(JTabbedPane pane) {
    super(SwingUtil.getRootFrame());
    this.pane = pane;
    initComponents();
    init();
  }
  
  public static Component show(Component component) {
    JTabbedPane pane = (JTabbedPane)SwingUtil.getOwnerComponent(JTabbedPane.class, component);
    if (pane != null) {
      SelectTabDialog dialog = new SelectTabDialog(pane);
      dialog.setVisible(true);
      if (dialog.modalResult == ModalResult.OK) {
        pane.setSelectedComponent(pane.getComponentAt(dialog.listViews.getSelectedIndex()));
        return pane.getComponentAt(dialog.listViews.getSelectedIndex());
      }
    }
    return null;
  }
  
  private void init() {
    int selectedTab = -1;
    listViews.removeAll();
    listViews.setModel(new DefaultListModel());
    if (pane != null) {
      for (int i=0; i<pane.getTabCount(); i++) {
        Component c = pane.getComponentAt(i);
        String text = pane.getTitleAt(i);
        if (c.isVisible()) {
          selectedTab = i;
        }
        ((DefaultListModel)listViews.getModel()).addElement(text);
      }
    }
    cmSelect.setEnabled(false);
    if (selectedTab != -1) {
      listViews.setSelectedIndex(selectedTab);
    }
    
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        listViews.requestFocus();
      }
    });

    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(cmCancel.getShortCut(), "cmCancel");
    getRootPane().getActionMap().put("cmCancel", cmCancel);
    getRootPane().setDefaultButton(buttonOk);
    SwingUtil.setButtonSizesTheSame(new AbstractButton[] {buttonOk, buttonCancel});
    pack();
    SwingUtil.centerWithinScreen(this);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmCancel = new pl.mpak.sky.gui.swing.Action();
    cmSelect = new pl.mpak.sky.gui.swing.Action();
    jScrollPane1 = new javax.swing.JScrollPane();
    listViews = new javax.swing.JList();
    buttonOk = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();

    cmCancel.setActionCommandKey("cmCancel");
    cmCancel.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmCancel.setText(stringManager.getString("cmCancel-text")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    cmSelect.setActionCommandKey("cmOk");
    cmSelect.setText(stringManager.getString("cmSelect-text")); // NOI18N
    cmSelect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmSelectActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("SelectTabDialog-title")); // NOI18N
    setModal(true);

    listViews.setFixedCellHeight(20);
    listViews.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listViewsValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(listViews);

    buttonOk.setAction(cmSelect);
    buttonOk.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonOk.setPreferredSize(new java.awt.Dimension(85, 25));

    buttonCancel.setAction(cmCancel);
    buttonCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonCancel.setPreferredSize(new java.awt.Dimension(85, 25));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void listViewsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listViewsValueChanged
    cmSelect.setEnabled(listViews.getSelectedIndex() != -1);
}//GEN-LAST:event_listViewsValueChanged

  private void cmSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmSelectActionPerformed
  modalResult = ModalResult.OK;
  dispose();
}//GEN-LAST:event_cmSelectActionPerformed

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  modalResult = ModalResult.CANCEL;
  dispose();
}//GEN-LAST:event_cmCancelActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private pl.mpak.sky.gui.swing.Action cmSelect;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList listViews;
  // End of variables declaration//GEN-END:variables
  
}
