/*
 * FontChoose.java
 *
 * Created on 11 listopad 2007, 15:16
 */

package orbada.gui.util;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.AbstractButton;
import orbada.Consts;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class FontChooser extends javax.swing.JDialog {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager(Consts.class);

  private String[] fontFamilies;
  private boolean updatingGroup;
  
  public static final String[] styleNames = new String[] {
    "Plain", "Italic", "Bold", "Bold + Italic" };
  
  public static final Integer[] styleValues = new Integer[] {
    new Integer(Font.PLAIN), new Integer(Font.ITALIC),
    new Integer(Font.BOLD), new Integer(Font.BOLD + Font.ITALIC) };
  
  public static final String[] sizeNames = new String[] {
    "8", "10", "11", "12", "14", "18", "20", "24", "28", "32", "40", "48", "56", "64", "72" };
  
  private Font font;
  private int modalResult = ModalResult.NONE;
  
  /**
   * Creates new form FontChoose
   * @param title
   * @param font
   */
  public FontChooser(String title, Font font) {
    super(SwingUtil.getRootFrame());
    this.font = font;
    initComponents();
    setTitle(title);
    init();
  }
  
  /**
   * <p>Pozwala wybraæ czcionkê
   * @param title
   * @param font
   * @return wybrany font lub null jeœli zaniechano
   */
  public static Font showDialog(String title, Font font) {
    FontChooser dialog = new FontChooser(title, font);
    dialog.setVisible(true);
    if (dialog.modalResult == ModalResult.OK) {
      return dialog.font;
    }
    return null;
  }
  
  private void init() {
    GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
    updatingGroup = true;
    try {
      fontFamilies = env.getAvailableFontFamilyNames();
      listFontFamilies.setListData(fontFamilies);
      listFontFamilies.setSelectedValue(font.getFamily(), true);
      listStyles.setListData(styleNames);
      listStyles.setSelectedValue(styleNames[font.getStyle()], true);
      listSizes.setListData(sizeNames);
      listSizes.setSelectedValue(String.valueOf(font.getSize()), true);
      textSize.setText(String.valueOf(font.getSize()));
    }
    finally {
      updatingGroup = false;
    }
    SwingUtil.setButtonSizesTheSame(new AbstractButton[] {buttonOk, buttonCancel});
    updatePreview();
    pack();
    SwingUtil.centerWithinScreen(this);
  }
  
  private void updatePreview() {
    if (!updatingGroup) {
      try {
        Font font_l = new Font(textFontFamily.getText(), styleValues[listStyles.getSelectedIndex()], Integer.parseInt(textSize.getText()));
        labelPreview.setFont(font_l);
      } catch (Throwable ex) {
        ExceptionUtil.processException(ex);
      }
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmOk = new pl.mpak.sky.gui.swing.Action();
    cmCancel = new pl.mpak.sky.gui.swing.Action();
    buttonOk = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listFontFamilies = new javax.swing.JList();
    textFontFamily = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel2 = new javax.swing.JLabel();
    textStyle = new pl.mpak.sky.gui.swing.comp.TextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    listStyles = new javax.swing.JList();
    jLabel3 = new javax.swing.JLabel();
    textSize = new pl.mpak.sky.gui.swing.comp.TextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    listSizes = new javax.swing.JList();
    jPanel1 = new javax.swing.JPanel();
    labelPreview = new javax.swing.JLabel();

    cmOk.setActionCommandKey("cmOk");
    cmOk.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
    cmOk.setText(stringManager.getString("cmOk-text")); // NOI18N
    cmOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmOkActionPerformed(evt);
      }
    });

    cmCancel.setActionCommandKey("cmCancel");
    cmCancel.setShortCut(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    cmCancel.setText(stringManager.getString("cmCancel-text")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle(stringManager.getString("FontChooser-title")); // NOI18N
    setModal(true);
    setResizable(false);

    buttonOk.setAction(cmOk);
    buttonOk.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonOk.setPreferredSize(new java.awt.Dimension(85, 25));

    buttonCancel.setAction(cmCancel);
    buttonCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
    buttonCancel.setPreferredSize(new java.awt.Dimension(85, 25));

    jLabel1.setText(stringManager.getString("FontChooser-font-dd")); // NOI18N

    listFontFamilies.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    listFontFamilies.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listFontFamiliesValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(listFontFamilies);

    textFontFamily.setEnabled(false);

    jLabel2.setText(stringManager.getString("FontChooser-style-dd")); // NOI18N

    textStyle.setEnabled(false);

    listStyles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    listStyles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listStylesValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(listStyles);

    jLabel3.setText(stringManager.getString("FontChooser-size-dd")); // NOI18N

    listSizes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    listSizes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listSizesValueChanged(evt);
      }
    });
    jScrollPane3.setViewportView(listSizes);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(stringManager.getString("FontChooser-preview"))); // NOI18N

    labelPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelPreview.setText(stringManager.getString("FontChooser-sample-preview")); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(labelPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1)
              .addComponent(textFontFamily, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
              .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel2)
                .addComponent(textStyle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(textSize, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textFontFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
private void listSizesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSizesValueChanged
  if (listSizes.getSelectedValue() != null) {
    textSize.setText(listSizes.getSelectedValue().toString());
    updatePreview();
  } else {
    textSize.setText("");
  }
}//GEN-LAST:event_listSizesValueChanged

private void listStylesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listStylesValueChanged
  if (listStyles.getSelectedValue() != null) {
    textStyle.setText(listStyles.getSelectedValue().toString());
    updatePreview();
  } else {
    textStyle.setText("");
  }
}//GEN-LAST:event_listStylesValueChanged

private void listFontFamiliesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFontFamiliesValueChanged
  if (listFontFamilies.getSelectedValue() != null) {
    textFontFamily.setText(listFontFamilies.getSelectedValue().toString());
    updatePreview();
  } else {
    textFontFamily.setText("");
  }
}//GEN-LAST:event_listFontFamiliesValueChanged

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  modalResult = ModalResult.CANCEL;
  dispose();
}//GEN-LAST:event_cmCancelActionPerformed

private void cmOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmOkActionPerformed
  try {
    font = new Font(textFontFamily.getText(), styleValues[listStyles.getSelectedIndex()], Integer.parseInt(textSize.getText()));
    modalResult = ModalResult.OK;
    dispose();
  } catch (Throwable ex) {
    MessageBox.show(stringManager.getString("error"), ex.getMessage(), ModalResult.OK);
  }
}//GEN-LAST:event_cmOkActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private pl.mpak.sky.gui.swing.Action cmOk;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JLabel labelPreview;
  private javax.swing.JList listFontFamilies;
  private javax.swing.JList listSizes;
  private javax.swing.JList listStyles;
  private pl.mpak.sky.gui.swing.comp.TextField textFontFamily;
  private pl.mpak.sky.gui.swing.comp.TextField textSize;
  private pl.mpak.sky.gui.swing.comp.TextField textStyle;
  // End of variables declaration//GEN-END:variables
  
}
