/*
 * ReportsPanelView.java
 *
 * Created on 26 paŸdziernik 2008, 14:37
 */

package pl.mpak.orbada.reports.gui;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.Closeable;
import java.io.IOException;
import javax.swing.tree.DefaultMutableTreeNode;
import pl.mpak.orbada.plugins.IViewAccesibilities;
import pl.mpak.orbada.reports.db.ReportRecord;
import pl.mpak.orbada.reports.gui.nodes.ReportTreeNodeInfo;
import pl.mpak.sky.gui.swing.Action;
import pl.mpak.sky.gui.swing.TabCloseComponent;
import pl.mpak.usedb.core.Database;
import pl.mpak.util.ExceptionUtil;

/**
 *
 * @author  akaluza
 */
public class ReportsPanelView extends javax.swing.JPanel implements Closeable {

  private IViewAccesibilities accesibilities;
  private boolean viewClosing = false;
  private ReportsTreePanel reportsTreePanel;

  /** Creates new form ReportsPanelView */
  public ReportsPanelView(IViewAccesibilities accesibilities) {
    this.accesibilities = accesibilities;
    initComponents();
    init();
  }

  private void init() {
    reportsTreePanel = new ReportsTreePanel(accesibilities.getPerspectiveAccesibilities(), cmRun);
    split.setLeftComponent(reportsTreePanel);
  }
  
  public Database getDatabase() {
    return accesibilities.getDatabase();
  }
  
  public void close() throws IOException {
    viewClosing = true;
    while (tabbedReports.getTabCount() > 0) {
      Component c = tabbedReports.getComponentAt(0);
      if (c instanceof Closeable) {
        try {
          ((Closeable) c).close();
        } catch (IOException ex) {
          ExceptionUtil.processException(ex);
        }
      }
      tabbedReports.remove(c);
    }
    reportsTreePanel.close();
    accesibilities = null;
  }
  
   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmRun = new pl.mpak.sky.gui.swing.Action();
    split = new javax.swing.JSplitPane();
    tabbedReports = new javax.swing.JTabbedPane();

    cmRun.setActionCommandKey("cmRun");
    cmRun.setSmallIcon(pl.mpak.sky.gui.swing.ImageManager.getImage("/res/icons/db_sql_execute16.gif")); // NOI18N
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/mpak/orbada/orbada-reports"); // NOI18N
    cmRun.setText(bundle.getString("run_report")); // NOI18N
    cmRun.setTooltip(bundle.getString("run_report_tooltip")); // NOI18N
    cmRun.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmRunActionPerformed(evt);
      }
    });

    setLayout(new java.awt.BorderLayout());

    split.setBorder(null);
    split.setDividerLocation(300);
    split.setContinuousLayout(true);
    split.setOneTouchExpandable(true);

    tabbedReports.setFocusable(false);
    split.setRightComponent(tabbedReports);

    add(split, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

private void cmRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmRunActionPerformed
  DefaultMutableTreeNode node = (DefaultMutableTreeNode)reportsTreePanel.getTree().getLastSelectedPathComponent();
  if (node != null) {
    ReportRecord report = ((ReportTreeNodeInfo)node.getUserObject()).getReport();
    final TableReportPanel panel = new TableReportPanel(accesibilities, report);
    TabCloseComponent tabClose = new TabCloseComponent(panel.getTitle(), new Action() {
      @Override
      public void actionPerformed(ActionEvent e) {
        try {
          panel.close();
        } catch (IOException ex) {
          ExceptionUtil.processException(ex);
        }
        tabbedReports.remove(panel);
      }
    });
    tabbedReports.addTab(panel.getTitle(), panel);
    tabbedReports.setTabComponentAt(tabbedReports.indexOfComponent(panel), tabClose);
    tabbedReports.setSelectedComponent(panel);
  }
}//GEN-LAST:event_cmRunActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.Action cmRun;
  private javax.swing.JSplitPane split;
  private javax.swing.JTabbedPane tabbedReports;
  // End of variables declaration//GEN-END:variables

}
