package pl.mpak.orbada.sqlite.gui.wizards;

import pl.mpak.orbada.sqlite.OrbadaSQLitePlugin;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author akaluza
 */
public class PragmaAutoVacuumWizard extends SqlCodeWizardPanel {

  private final StringManager stringManager = StringManagerFactory.getStringManager("sqlite");

  private Database database;

  public PragmaAutoVacuumWizard(Database database) {
    this.database = database;
    initComponents();
    init();
  }

  private void init() {
  }

  public void wizardShow() {
    try {
      Query query = database.createQuery("PRAGMA AUTO_VACUUM");
      try {
        if ("0".equals(query.fieldByName("auto_vacuum").getString())) {
          textVacuum.setText("NONE");
        }
        else if ("1".equals(query.fieldByName("auto_vacuum").getString())) {
          textVacuum.setText("FULL");
        }
        else if ("2".equals(query.fieldByName("auto_vacuum").getString())) {
          textVacuum.setText("INCREMENTAL");
        }
        else {
          textVacuum.setText(query.fieldByName("auto_vacuum").getString());
        }
      }
      finally {
        query.close();
      }
    } catch (Exception ex) {
    }
  }

  public String getDialogTitle() {
    return stringManager.getString("auto-vacuum");
  }

  public String getTabTitle() {
    return stringManager.getString("setting");
  }

  public String getSqlCode() {
    return "PRAGMA AUTO_VACUUM = " +textVacuum.getText() +"\n/\nVACUUM\n/";
  }

  public boolean execute() {
    try {
      database.executeScript(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    textVacuum = new pl.mpak.sky.gui.swing.comp.ComboBox();

    jLabel1.setText(stringManager.getString("auto-vacuum-dd")); // NOI18N

    textVacuum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "FULL", "INCREMENTAL" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textVacuum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(120, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(textVacuum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(41, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private pl.mpak.sky.gui.swing.comp.ComboBox textVacuum;
  // End of variables declaration//GEN-END:variables

}
