/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourcePanel.java
 *
 * Created on 2009-03-27, 19:32:39
 */
package pl.mpak.mpak.oracle.tune.gui.profiler;

import java.awt.Color;
import java.io.Closeable;
import java.io.IOException;
import pl.mpak.orbada.oracle.util.SourceCreator;
import pl.mpak.orbada.plugins.IViewAccesibilities;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.sky.gui.swing.syntax.SyntaxDocument.LineMark;
import pl.mpak.util.StringUtil;

/**
 *
 * @author akaluza
 */
public class SourcePanel extends javax.swing.JPanel implements Closeable {

  private IViewAccesibilities accesibilities;
  private String schemaName;
  private String objectType;
  private String objectName;
  private SourceCreator sourceCreator;
  private LineMark lineMark;

  /** Creates new form SourcePanel */
  public SourcePanel(IViewAccesibilities accesibilities) {
    this.accesibilities = accesibilities;
    initComponents();
    init();
  }

  private void init() {
    source.setDatabase(accesibilities.getDatabase());
    sourceCreator = new SourceCreator(accesibilities.getDatabase(), source);
    lineMark = new LineMark(-1, Color.getColor("activeCaption", new Color(204, 204, 255)), pl.mpak.sky.gui.swing.ImageManager.getImage("/pl/mpak/res/icons/line_point.gif"));
  }

  public void refresh(String schemaName, String objectType, String objectName) {
    if (!StringUtil.equals(this.schemaName, schemaName) || !StringUtil.equals(this.objectType, objectType) || !StringUtil.equals(this.objectName, objectName)) {
      this.schemaName = schemaName;
      this.objectType = objectType;
      this.objectName = objectName;
      if (!"ANONYMOUS BLOCK".equals(objectType)) {
        sourceCreator.getSource(schemaName, objectType, objectName);
      }
      else {
        source.setDatabaseObject(schemaName, objectType, objectName, "");
      }
    }
  }

  public void close() throws IOException {
    source.setDatabase(null);
    source = null;
    sourceCreator = null;
  }

  public void gotoLine(final int lineNo) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        source.removeLineMark(lineMark);
        lineMark.setLine(lineNo);
        source.setLineMark(lineMark);
        int offset = source.getEditorArea().getLineStartOffset(lineNo -1);
        source.getEditorArea().setCaretPosition(offset, true);
        source.repaint();
      }
    });
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    source = new pl.mpak.orbada.gui.comps.OrbadaSyntaxTextArea();

    setLayout(new java.awt.BorderLayout());

    source.setEditable(false);
    add(source, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.orbada.gui.comps.OrbadaSyntaxTextArea source;
  // End of variables declaration//GEN-END:variables
}
