package pl.mpak.orbada.oracle.gui.wizards;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.oracle.services.OracleDbInfoProvider;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class CreateDbLinkWizard extends SqlCodeWizardPanel {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOraclePlugin.class);

  private Database database;
  private String schemaName;
  
  public CreateDbLinkWizard(Database database, String schemaName) {
    this.database = database;
    this.schemaName = schemaName;
    initComponents();
    init();
  }
  
  private void init() {
    schemaName = schemaName == null ? OracleDbInfoProvider.getCurrentSchema(database) : schemaName;
  }
  
  public void wizardShow() {
  }
  
  public String getDialogTitle() {
    return stringManager.getString("CreateDbLinkWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("CreateDbLinkWizard-tab-title");
  }
  
  public String getSqlCode() {
    getResultMap().put("object_name", textName.getText());
    return 
      "CREATE" +(checkShared.isSelected() ? " SHARED" : "") +(checkPublic.isSelected() ? " PUBLIC" : "") +" DATABASE LINK " +textName.getText() +"\n" +
      "  CONNECT TO " +(checkCurrentUser.isSelected() ? "CURRENT_USER" : textConnectUser.getText() +" IDENTIFIED BY " +textConnectPassword.getText()) +
      (checkShared.isSelected() ? "\n  AUTHENTICATED BY " +SQLUtil.createSqlName(textSharedUser.getText()) +" IDENTIFIED BY " +textSharedPassword.getText() : "") +"\n" +
      "  USING '" +textHost.getText() +"'";
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    textName = new pl.mpak.sky.gui.swing.comp.TextField();
    checkPublic = new javax.swing.JCheckBox();
    checkCurrentUser = new javax.swing.JCheckBox();
    labelConnectUser = new javax.swing.JLabel();
    textConnectUser = new pl.mpak.sky.gui.swing.comp.TextField();
    labelConnectPassword = new javax.swing.JLabel();
    textConnectPassword = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel4 = new javax.swing.JLabel();
    textHost = new pl.mpak.sky.gui.swing.comp.TextField();
    checkShared = new javax.swing.JCheckBox();
    labelSharedUser = new javax.swing.JLabel();
    textSharedUser = new pl.mpak.sky.gui.swing.comp.TextField();
    labelSharedPassword = new javax.swing.JLabel();
    textSharedPassword = new pl.mpak.sky.gui.swing.comp.TextField();

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText(stringManager.getString("db-link-name-dd")); // NOI18N

    checkPublic.setText(stringManager.getString("public")); // NOI18N

    checkCurrentUser.setText(stringManager.getString("current-user-dd")); // NOI18N
    checkCurrentUser.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        checkCurrentUserItemStateChanged(evt);
      }
    });

    labelConnectUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelConnectUser.setText(stringManager.getString("user-dd")); // NOI18N

    labelConnectPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelConnectPassword.setText(stringManager.getString("password-dd")); // NOI18N

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText(stringManager.getString("destination-server-dd")); // NOI18N

    checkShared.setText(stringManager.getString("shared-connection")); // NOI18N
    checkShared.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        checkSharedItemStateChanged(evt);
      }
    });

    labelSharedUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelSharedUser.setText(stringManager.getString("user-dd")); // NOI18N
    labelSharedUser.setEnabled(false);

    textSharedUser.setEnabled(false);

    labelSharedPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelSharedPassword.setText(stringManager.getString("password-dd")); // NOI18N
    labelSharedPassword.setEnabled(false);

    textSharedPassword.setEnabled(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(119, 119, 119)
            .addComponent(checkCurrentUser))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelConnectUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textConnectUser, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkPublic)
              .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textHost, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelConnectPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkShared)
              .addComponent(textConnectPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelSharedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textSharedUser, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelSharedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textSharedPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkPublic)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(textHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkCurrentUser)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelConnectUser)
          .addComponent(textConnectUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelConnectPassword)
          .addComponent(textConnectPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkShared)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelSharedUser)
          .addComponent(textSharedUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelSharedPassword)
          .addComponent(textSharedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void checkSharedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSharedItemStateChanged
    labelSharedUser.setEnabled(checkShared.isSelected());
    labelSharedPassword.setEnabled(checkShared.isSelected());
    textSharedUser.setEnabled(checkShared.isSelected());
    textSharedPassword.setEnabled(checkShared.isSelected());
  }//GEN-LAST:event_checkSharedItemStateChanged

  private void checkCurrentUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkCurrentUserItemStateChanged
    labelConnectUser.setEnabled(!checkCurrentUser.isSelected());
    labelConnectPassword.setEnabled(!checkCurrentUser.isSelected());
    textConnectUser.setEnabled(!checkCurrentUser.isSelected());
    textConnectPassword.setEnabled(!checkCurrentUser.isSelected());
  }//GEN-LAST:event_checkCurrentUserItemStateChanged
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkCurrentUser;
  private javax.swing.JCheckBox checkPublic;
  private javax.swing.JCheckBox checkShared;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel labelConnectPassword;
  private javax.swing.JLabel labelConnectUser;
  private javax.swing.JLabel labelSharedPassword;
  private javax.swing.JLabel labelSharedUser;
  private pl.mpak.sky.gui.swing.comp.TextField textConnectPassword;
  private pl.mpak.sky.gui.swing.comp.TextField textConnectUser;
  private pl.mpak.sky.gui.swing.comp.TextField textHost;
  private pl.mpak.sky.gui.swing.comp.TextField textName;
  private pl.mpak.sky.gui.swing.comp.TextField textSharedPassword;
  private pl.mpak.sky.gui.swing.comp.TextField textSharedUser;
  // End of variables declaration//GEN-END:variables
  
}
