package pl.mpak.orbada.oracle.gui.wizards;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.oracle.dbinfo.OracleSchemaInfo;
import pl.mpak.orbada.oracle.gui.util.ObjectComboBoxModel;
import pl.mpak.orbada.oracle.gui.util.SchemaComboBoxModel;
import pl.mpak.orbada.oracle.gui.util.SchemaItemListener;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class CreateSynonymWizard extends SqlCodeWizardPanel {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOraclePlugin.class);

  private Database database;
  private String schemaName;
  
  public CreateSynonymWizard(Database database, String schemaName) {
    this.database = database;
    this.schemaName = schemaName;
    initComponents();
    init();
  }
  
  private void init() {
    comboSchemas.setModel(new SchemaComboBoxModel(database));
    comboObjects.setModel(new ObjectComboBoxModel(database));

    comboSchemas.addItemListener(new SchemaItemListener() {
      public void itemChanged(OracleSchemaInfo info) {
        ((ObjectComboBoxModel)comboObjects.getModel()).change(info.getName());
      }
    });
  }
  
  public void wizardShow() {
    ((SchemaComboBoxModel)comboSchemas.getModel()).change();
    ((SchemaComboBoxModel)comboSchemas.getModel()).select(schemaName, comboSchemas);
  }
  
  public String getDialogTitle() {
    return stringManager.getString("CreateSynonymWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("CreateSynonymWizard-tab-title");
  }
  
  public String getSqlCode() {
    getResultMap().put("object_name", textName.getText());
    return
      "CREATE" +(checkPublic.isSelected() ? " PUBLIC" : "") +" SYNONYM " +
      textName.getText() +" FOR " +
      (radioBaseObject.isSelected() ? SQLUtil.createSqlName(comboSchemas.getSelectedItem().toString(), comboObjects.getSelectedItem().toString()) : "") +
      (radioNamedObject.isSelected() ? SQLUtil.createSqlName(comboSchemas.getSelectedItem().toString()) +"." +textObjectName.getText() : "");
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    groupObject = new javax.swing.ButtonGroup();
    jLabel5 = new javax.swing.JLabel();
    textName = new pl.mpak.sky.gui.swing.comp.TextField();
    checkPublic = new javax.swing.JCheckBox();
    jLabel6 = new javax.swing.JLabel();
    comboSchemas = new javax.swing.JComboBox();
    comboObjects = new javax.swing.JComboBox();
    textObjectName = new pl.mpak.sky.gui.swing.comp.TextField();
    radioBaseObject = new javax.swing.JRadioButton();
    radioNamedObject = new javax.swing.JRadioButton();

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText(stringManager.getString("synonym-name-dd")); // NOI18N

    checkPublic.setText(stringManager.getString("public")); // NOI18N

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText(stringManager.getString("object-schema-dd")); // NOI18N

    comboSchemas.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        comboSchemasItemStateChanged(evt);
      }
    });

    comboObjects.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        comboObjectsItemStateChanged(evt);
      }
    });

    groupObject.add(radioBaseObject);
    radioBaseObject.setText(stringManager.getString("base-object")); // NOI18N
    radioBaseObject.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    radioBaseObject.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

    groupObject.add(radioNamedObject);
    radioNamedObject.setSelected(true);
    radioNamedObject.setText(stringManager.getString("object-name")); // NOI18N
    radioNamedObject.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    radioNamedObject.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkPublic)
              .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(radioNamedObject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(radioBaseObject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(textObjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
              .addComponent(comboObjects, 0, 204, Short.MAX_VALUE)
              .addComponent(comboSchemas, 0, 204, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkPublic)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(comboSchemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(radioBaseObject)
          .addComponent(comboObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioNamedObject)
          .addComponent(textObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void comboSchemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSchemasItemStateChanged
    // TODO add your handling code here:
  }//GEN-LAST:event_comboSchemasItemStateChanged

  private void comboObjectsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboObjectsItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_comboObjectsItemStateChanged
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkPublic;
  private javax.swing.JComboBox comboObjects;
  private javax.swing.JComboBox comboSchemas;
  private javax.swing.ButtonGroup groupObject;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JRadioButton radioBaseObject;
  private javax.swing.JRadioButton radioNamedObject;
  private pl.mpak.sky.gui.swing.comp.TextField textName;
  private pl.mpak.sky.gui.swing.comp.TextField textObjectName;
  // End of variables declaration//GEN-END:variables
  
}
