package pl.mpak.orbada.oracle.gui.wizards;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.oracle.dbinfo.OracleRecyclebinInfo;
import pl.mpak.orbada.oracle.gui.util.RecyclebinComboBoxModel;
import pl.mpak.orbada.oracle.services.OracleDbInfoProvider;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class PurgeObjectWizard extends SqlCodeWizardPanel {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaOraclePlugin.class);

  private Database database;
  private String objectName;
  private String schemaName;
  
  public PurgeObjectWizard(Database database, String schemaName, String objectName) {
    this.database = database;
    this.schemaName = schemaName;
    this.objectName = objectName;
    initComponents();
    init();
  }
  
  public PurgeObjectWizard(Database database, String objectName) {
    this(database, null, objectName);
  }
  
  private void init() {
    schemaName = (schemaName == null ? OracleDbInfoProvider.getCurrentSchema(database) : schemaName);
    comboObjects.setModel(new RecyclebinComboBoxModel(database));
  }
  
  public void wizardShow() {
    ((RecyclebinComboBoxModel)comboObjects.getModel()).change();
    ((RecyclebinComboBoxModel)comboObjects.getModel()).select(objectName, comboObjects);
  }
  
  public String getDialogTitle() {
    return stringManager.getString("PurgeObjectWizard-dialog-title");
  }
  
  public String getTabTitle() {
    return stringManager.getString("PurgeObjectWizard-tab-title");
  }
  
  public String getSqlCode() {
    OracleRecyclebinInfo info = (OracleRecyclebinInfo)comboObjects.getSelectedItem();
    if (info != null) {
      return
        "PURGE " +info.getType() +" " +
        SQLUtil.createSqlName(schemaName, comboObjects.getSelectedItem().toString());
    }
    else {
      return "";
    }
  }
  
  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    comboObjects = new javax.swing.JComboBox();

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("object-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(comboObjects, 0, 196, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(comboObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox comboObjects;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables
  
}
