/*
 * TaskPanel.java
 *
 * Created on 12 listopad 2007, 18:30
 */

package pl.mpak.orbada.system.gui;

import java.sql.SQLException;
import pl.mpak.orbada.system.OrbadaSystemPlugin;
import pl.mpak.sky.gui.swing.SwingUtil;
import pl.mpak.usedb.core.Command;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;
import pl.mpak.util.timer.Timer;

/**
 *
 * @author  akaluza
 */
public class CommandPanel extends javax.swing.JPanel {
  
  private final static StringManager stringManager = StringManagerFactory.getStringManager("system");
  private Command command;
  private Timer timer;
  
  /** 
   * Creates new form TaskPanel 
   * @param task 
   */
  public CommandPanel(Command query) {
    this.command = query;
    initComponents();
    init();
  }
  
  private void init() {
    setFocusable(true);
  }

  public void update() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        updateStatus();
      }
    });
  }
  
  public void updateStatus() {
    setBackground(SwingUtil.addColor(getBackground(), 120, -10, -10));
    labelDatabase.setText(command.getDatabase().getPublicName());
    textQuery.setText(command.getSqlText());
    textQuery.setCaretPosition(0);
    labelStatus.setText(stringManager.getString("cxecuting"));
  }
  
  public void close() {
  }
  
  public Command getCommand() {
    return command;
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cmCancel = new pl.mpak.sky.gui.swing.Action();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    textQuery = new javax.swing.JTextArea();
    labelDatabase = new javax.swing.JLabel();
    labelStatus = new javax.swing.JLabel();

    cmCancel.setActionCommandKey("cmCancel");
    cmCancel.setSmallIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/stop10.gif"))); // NOI18N
    cmCancel.setText(stringManager.getString("cancel")); // NOI18N
    cmCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmCancelActionPerformed(evt);
      }
    });

    setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, javax.swing.UIManager.getDefaults().getColor("controlShadow")));

    jButton1.setAction(cmCancel);
    jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jButton1.setPreferredSize(new java.awt.Dimension(60, 20));

    textQuery.setColumns(20);
    textQuery.setEditable(false);
    textQuery.setFont(new java.awt.Font("Courier New", 0, 11));
    textQuery.setRows(5);
    jScrollPane1.setViewportView(textQuery);

    labelDatabase.setText("labelDatabase");

    labelStatus.setText("labelStatus");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(labelDatabase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelDatabase)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelStatus))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

private void cmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCancelActionPerformed
  try {
    command.cancel();
  } catch (SQLException ex) {
    ExceptionUtil.processException(ex);
  }
}//GEN-LAST:event_cmCancelActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.Action cmCancel;
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel labelDatabase;
  private javax.swing.JLabel labelStatus;
  private javax.swing.JTextArea textQuery;
  // End of variables declaration//GEN-END:variables
  
}
