/*
 * TaskExecutionPanel.java
 *
 * Created on 12 listopad 2007, 18:27
 */

package pl.mpak.orbada.system.gui;

import java.util.ArrayList;
import pl.mpak.orbada.system.serives.SystemStatusBarProvider;
import pl.mpak.util.task.Task;
import pl.mpak.util.task.TaskPoolContainerEvent;
import pl.mpak.util.task.TaskPoolContainerListener;
import pl.mpak.util.task.TaskPoolEvent;
import pl.mpak.util.task.TaskPoolListener;
import pl.mpak.util.task.TaskPoolManager;

/**
 *
 * @author  akaluza
 */
public class TaskExecutionPanel extends javax.swing.JPanel {
  
  private TaskPoolContainerListener containerListener;
  private TaskPoolListener poolListener;
  
  /** Creates new form TaskExecutionPanel */
  public TaskExecutionPanel() {
    initComponents();
    init();
  }
  
  private void init() {
    ArrayList<Task> taskList = SystemStatusBarProvider.getTaskList();
    synchronized (taskList) {
      for (int i=0; i<taskList.size(); i++) {
        panelTasks.add(new TaskPanel(taskList.get(i)));
      }
    }
    containerListener = new TaskPoolContainerListener() {
      public void addTask(final TaskPoolContainerEvent e) {
        synchronized (panelTasks) {
          panelTasks.add(new TaskPanel(e.getTask()));
        }
        refreshList();
      }
      public void removeTask(pl.mpak.util.task.TaskPoolContainerEvent e) {
      }
    };
    poolListener = new TaskPoolListener() {
      public void beginPool(TaskPoolEvent e) {
      }
      public void endPool(TaskPoolEvent e) {
      }
      public void beginTask(TaskPoolEvent e) {
        synchronized (panelTasks) {
          for (int i = 0; i < panelTasks.getComponentCount(); i++) {
            final TaskPanel tp = (TaskPanel) panelTasks.getComponent(i);
            if (tp.getTask().equals(e.getTask())) {
              tp.updateStatus();
              break;
            }
          }
        }
        refreshList();
      }
      public void endTask(TaskPoolEvent e) {
        synchronized (panelTasks) {
          for (int i = 0; i < panelTasks.getComponentCount(); i++) {
            final TaskPanel tp = (TaskPanel) panelTasks.getComponent(i);
            if (tp.getTask().equals(e.getTask())) {
              panelTasks.remove(tp);
              break;
            }
          }
        }
        refreshList();
      }
    };
    TaskPoolManager.addTaskPoolContainerListener(containerListener);
    TaskPoolManager.addTaskPoolListener(poolListener);
  }
  
  private void refreshList() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        panelTasks.revalidate();
        panelTasks.repaint();
      }
    });
  }
  
  public void close() {
    TaskPoolManager.removeTaskPoolListener(poolListener);
    TaskPoolManager.removeTaskPoolContainerListener(containerListener);
    panelTasks.removeAll();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    panelTasks = new javax.swing.JPanel();

    panelTasks.setLayout(new javax.swing.BoxLayout(panelTasks, javax.swing.BoxLayout.Y_AXIS));
    jScrollPane1.setViewportView(panelTasks);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel panelTasks;
  // End of variables declaration//GEN-END:variables
  
}
