package pl.mpak.orbada.oracle.gui.settings;

import pl.mpak.orbada.oracle.OrbadaOraclePlugin;
import pl.mpak.orbada.plugins.IApplication;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.plugins.ISettingsComponent;
import pl.mpak.usedb.core.Database;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class SourceCreatorSettingsPanel extends javax.swing.JPanel implements ISettingsComponent {

  private final StringManager stringManager = StringManagerFactory.getStringManager("oracle");

  public final static String settingsName = "oracle-source-creator-settings";
  
  private IApplication application;
  private ISettings settings;
  private Database database;

  /** Creates new form DatabaseSettingsPanel */
  public SourceCreatorSettingsPanel(IApplication application, Database database) {
    this.application = application;
    this.database = database;
    initComponents();
    init();
  }
  
  private void init() {
    settings = application.getSettings(database.getUserProperties().getProperty("schemaId"), settingsName);
    restoreSettings();
  }
  
  public void restoreSettings() {
    checkALL_PRETTY.setSelected(settings.getValue("ALL-PRETTY", checkALL_PRETTY.isSelected()));
    checkALL_SQLTERMINATOR.setSelected(settings.getValue("ALL-SQLTERMINATOR", checkALL_SQLTERMINATOR.isSelected()));
    checkALL_LATEST.setSelected(settings.getValue("ALL-LATEST", checkALL_LATEST.isSelected()));

    checkTABLE_SEGMENT_ATTRIBUTES.setSelected(settings.getValue("TABLE-SEGMENT_ATTRIBUTES", checkTABLE_SEGMENT_ATTRIBUTES.isSelected()));
    checkTABLE_STORAGE.setSelected(settings.getValue("TABLE-STORAGE", checkTABLE_STORAGE.isSelected()));
    checkTABLE_TABLESPACE.setSelected(settings.getValue("TABLE-TABLESPACE", checkTABLE_TABLESPACE.isSelected()));
    checkTABLE_CONSTRAINTS.setSelected(settings.getValue("TABLE-CONSTRAINTS", checkTABLE_CONSTRAINTS.isSelected()));
    checkTABLE_REF_CONSTRAINTS.setSelected(settings.getValue("TABLE-REF_CONSTRAINTS", checkTABLE_REF_CONSTRAINTS.isSelected()));
    checkTABLE_CONSTRAINTS_AS_ALTER.setSelected(settings.getValue("TABLE-CONSTRAINTS_AS_ALTER", checkTABLE_CONSTRAINTS_AS_ALTER.isSelected()));
    checkTABLE_SIZE_BYTE_KEYWORD.setSelected(settings.getValue("TABLE-SIZE_BYTE_KEYWORD", checkTABLE_SIZE_BYTE_KEYWORD.isSelected()));

    checkINDEX_SEGMENT_ATTRIBUTES.setSelected(settings.getValue("INDEX-SEGMENT_ATTRIBUTES", checkINDEX_SEGMENT_ATTRIBUTES.isSelected()));
    checkINDEX_STORAGE.setSelected(settings.getValue("INDEX-STORAGE", checkINDEX_STORAGE.isSelected()));
    checkINDEX_TABLESPACE.setSelected(settings.getValue("INDEX-TABLESPACE", checkINDEX_TABLESPACE.isSelected()));

    checkVIEW_FORCE.setSelected(settings.getValue("VIEW-FORCE", checkVIEW_FORCE.isSelected()));
  }

  public void applySettings() {
    settings.setValue("ALL-PRETTY", checkALL_PRETTY.isSelected());
    settings.setValue("ALL-SQLTERMINATOR", checkALL_SQLTERMINATOR.isSelected());
    settings.setValue("ALL-LATEST", checkALL_LATEST.isSelected());

    settings.setValue("TABLE-SEGMENT_ATTRIBUTES", checkTABLE_SEGMENT_ATTRIBUTES.isSelected());
    settings.setValue("TABLE-STORAGE", checkTABLE_STORAGE.isSelected());
    settings.setValue("TABLE-TABLESPACE", checkTABLE_TABLESPACE.isSelected());
    settings.setValue("TABLE-CONSTRAINTS", checkTABLE_CONSTRAINTS.isSelected());
    settings.setValue("TABLE-REF_CONSTRAINTS", checkTABLE_REF_CONSTRAINTS.isSelected());
    settings.setValue("TABLE-CONSTRAINTS_AS_ALTER", checkTABLE_CONSTRAINTS_AS_ALTER.isSelected());
    settings.setValue("TABLE-SIZE_BYTE_KEYWORD", checkTABLE_SIZE_BYTE_KEYWORD.isSelected());

    settings.setValue("INDEX-SEGMENT_ATTRIBUTES", checkINDEX_SEGMENT_ATTRIBUTES.isSelected());
    settings.setValue("INDEX-STORAGE", checkINDEX_STORAGE.isSelected());
    settings.setValue("INDEX-TABLESPACE", checkINDEX_TABLESPACE.isSelected());

    settings.setValue("VIEW-FORCE", checkVIEW_FORCE.isSelected());
    
    settings.store();
  }

  public void cancelSettings() {
    restoreSettings();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        checkALL_PRETTY = new javax.swing.JCheckBox();
        checkALL_SQLTERMINATOR = new javax.swing.JCheckBox();
        checkALL_LATEST = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        checkINDEX_SEGMENT_ATTRIBUTES = new javax.swing.JCheckBox();
        checkINDEX_STORAGE = new javax.swing.JCheckBox();
        checkINDEX_TABLESPACE = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        checkTABLE_SEGMENT_ATTRIBUTES = new javax.swing.JCheckBox();
        checkTABLE_STORAGE = new javax.swing.JCheckBox();
        checkTABLE_TABLESPACE = new javax.swing.JCheckBox();
        checkTABLE_CONSTRAINTS = new javax.swing.JCheckBox();
        checkTABLE_REF_CONSTRAINTS = new javax.swing.JCheckBox();
        checkTABLE_CONSTRAINTS_AS_ALTER = new javax.swing.JCheckBox();
        checkTABLE_SIZE_BYTE_KEYWORD = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        checkVIEW_FORCE = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(stringManager.getString("SourceCreatorSettingsPanel-all-objects"))); // NOI18N

        checkALL_PRETTY.setSelected(true);
        checkALL_PRETTY.setText(stringManager.getString("SourceCreatorSettingsPanel-checkALL_PRETTY-text")); // NOI18N

        checkALL_SQLTERMINATOR.setText(stringManager.getString("SourceCreatorSettingsPanel-checkALL_SQLTERMINATOR-text")); // NOI18N

        checkALL_LATEST.setText(stringManager.getString("SourceCreatorSettingsPanel-checkALL_LATEST-text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkALL_LATEST, javax.swing.GroupLayout.PREFERRED_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(checkALL_SQLTERMINATOR, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(checkALL_PRETTY, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(checkALL_PRETTY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkALL_SQLTERMINATOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkALL_LATEST)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(stringManager.getString("SourceCreatorSettingsPanel-indexes"))); // NOI18N

        checkINDEX_SEGMENT_ATTRIBUTES.setSelected(true);
        checkINDEX_SEGMENT_ATTRIBUTES.setText(stringManager.getString("SourceCreatorSettingsPanel-checkINDEX_SEGMENT_ATRRIBUTES-text")); // NOI18N

        checkINDEX_STORAGE.setSelected(true);
        checkINDEX_STORAGE.setText(stringManager.getString("SourceCreatorSettingsPanel-checkINDEX_STORAGE-text")); // NOI18N

        checkINDEX_TABLESPACE.setSelected(true);
        checkINDEX_TABLESPACE.setText(stringManager.getString("SourceCreatorSettingsPanel-checkINDEX_TABLESPACE-text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkINDEX_SEGMENT_ATTRIBUTES, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkINDEX_TABLESPACE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(checkINDEX_STORAGE, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(checkINDEX_SEGMENT_ATTRIBUTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkINDEX_STORAGE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkINDEX_TABLESPACE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(stringManager.getString("SourceCreatorSettingsPanel-tables"))); // NOI18N

        checkTABLE_SEGMENT_ATTRIBUTES.setSelected(true);
        checkTABLE_SEGMENT_ATTRIBUTES.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_SEGMENT_ATTRIBUTES-text")); // NOI18N

        checkTABLE_STORAGE.setSelected(true);
        checkTABLE_STORAGE.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_STORAGE-text")); // NOI18N

        checkTABLE_TABLESPACE.setSelected(true);
        checkTABLE_TABLESPACE.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_TABLESPACE-text")); // NOI18N

        checkTABLE_CONSTRAINTS.setSelected(true);
        checkTABLE_CONSTRAINTS.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_CONSTRAINTS-text")); // NOI18N

        checkTABLE_REF_CONSTRAINTS.setSelected(true);
        checkTABLE_REF_CONSTRAINTS.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_REF_CONSTRAINTS-text")); // NOI18N

        checkTABLE_CONSTRAINTS_AS_ALTER.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_CONSTRAINTS_AS_ALTER-text")); // NOI18N

        checkTABLE_SIZE_BYTE_KEYWORD.setText(stringManager.getString("SourceCreatorSettingsPanel-checkTABLE_SIZE_BYTE_KEYWORD-text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTABLE_CONSTRAINTS, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(checkTABLE_SEGMENT_ATTRIBUTES, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTABLE_TABLESPACE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(checkTABLE_STORAGE, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
                    .addComponent(checkTABLE_REF_CONSTRAINTS, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(checkTABLE_CONSTRAINTS_AS_ALTER, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(checkTABLE_SIZE_BYTE_KEYWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(checkTABLE_SEGMENT_ATTRIBUTES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_STORAGE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_TABLESPACE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_CONSTRAINTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_REF_CONSTRAINTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_CONSTRAINTS_AS_ALTER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTABLE_SIZE_BYTE_KEYWORD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(stringManager.getString("SourceCreatorSettingsPanel-views"))); // NOI18N

        checkVIEW_FORCE.setText(stringManager.getString("SourceCreatorSettingsPanel-checkVIEW_FORCE-text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkVIEW_FORCE, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(checkVIEW_FORCE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkALL_LATEST;
    private javax.swing.JCheckBox checkALL_PRETTY;
    private javax.swing.JCheckBox checkALL_SQLTERMINATOR;
    private javax.swing.JCheckBox checkINDEX_SEGMENT_ATTRIBUTES;
    private javax.swing.JCheckBox checkINDEX_STORAGE;
    private javax.swing.JCheckBox checkINDEX_TABLESPACE;
    private javax.swing.JCheckBox checkTABLE_CONSTRAINTS;
    private javax.swing.JCheckBox checkTABLE_CONSTRAINTS_AS_ALTER;
    private javax.swing.JCheckBox checkTABLE_REF_CONSTRAINTS;
    private javax.swing.JCheckBox checkTABLE_SEGMENT_ATTRIBUTES;
    private javax.swing.JCheckBox checkTABLE_SIZE_BYTE_KEYWORD;
    private javax.swing.JCheckBox checkTABLE_STORAGE;
    private javax.swing.JCheckBox checkTABLE_TABLESPACE;
    private javax.swing.JCheckBox checkVIEW_FORCE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
  
}
