package pl.mpak.orbada.firebird.gui.wizards;

import java.util.HashMap;
import orbada.core.Application;
import pl.mpak.orbada.db.Template;
import pl.mpak.orbada.firebird.OrbadaFirebirdPlugin;
import pl.mpak.orbada.firebird.services.FirebirdTemplatesSettingsProvider;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.universal.gui.util.TableComboBoxModel;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class CreateTriggerWizard extends SqlCodeWizardPanel {

  private StringManager stringManager = StringManagerFactory.getStringManager(OrbadaFirebirdPlugin.class);

  private Database database;
  private String tableName;
  private Template template;

  public CreateTriggerWizard(Database database, String tableName) {
    this.database = database;
    this.tableName = tableName;
    initComponents();
    init();
  }

  private void init() {
    comboTables.setModel(new TableComboBoxModel(database));
  }

  public void wizardShow() {
    ISettings oracle = Application.get().getSettings(FirebirdTemplatesSettingsProvider.settingsName);
    template = new Template(Application.get().getOrbadaDatabase()).loadByName(oracle.getValue(FirebirdTemplatesSettingsProvider.setTrigger, "firebird-trigger"));

    ((TableComboBoxModel)comboTables.getModel()).change(null);
    ((TableComboBoxModel)comboTables.getModel()).select(tableName, comboTables);
  }
  
  public String getDialogTitle() {
    return stringManager.getString("CreateTriggerWizard-dialog-title");
  }

  public String getTabTitle() {
    return stringManager.getString("CreateTriggerWizard-tab-title");
  }

  public String getSqlCode() {
    getResultMap().put("object_name", textName.getText());
    tableName = SQLUtil.createSqlName(comboTables.getSelectedItem().toString());
    String idu = "";
    if (checkInsert.isSelected()) {
      idu = idu +" INSERT";
    }
    else if (checkDelete.isSelected()) {
      idu = idu +" DELETE";
    }
    else if (checkUpdate.isSelected()) {
      idu = idu +" UPDATE";
    }
    String type = 
      "  " +(checkBefore.isSelected() ? "BEFORE" : "AFTER") +idu +
      ("".equals(textPosition.getText()) ? "" : " POSITION " +textPosition.getText());
    if (template == null) {
      return
        "CREATE TRIGGER " +textName.getText() +" FOR " +tableName +"\n" +
        (checkInactive.isSelected() ? "  INACTIVE\n" : "") +
        type +" AS\n" +
        ("".equals(textDescription.getText()) ? "" : "/* " +textDescription.getText() +" */\n") +
        "BEGIN\n" +
//        "  SUSPEND;\n" +
        "END;";
    }
    else {
      HashMap<String, String> map = new HashMap<String, String>();
      map.put("&name", textName.getText());
      map.put("&tablename", tableName);
      map.put("&type", type);
      map.put("&body", "");
      map.put("&description", textDescription.getText());
      return template.expand(map);
    }
  }

  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    groupBA = new javax.swing.ButtonGroup();
    groupIUD = new javax.swing.ButtonGroup();
    jLabel2 = new javax.swing.JLabel();
    comboTables = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    textName = new pl.mpak.sky.gui.swing.comp.TextField();
    checkInactive = new javax.swing.JCheckBox();
    checkBefore = new javax.swing.JRadioButton();
    checkAfter = new javax.swing.JRadioButton();
    checkInsert = new javax.swing.JRadioButton();
    checkUpdate = new javax.swing.JRadioButton();
    checkDelete = new javax.swing.JRadioButton();
    textPosition = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    textDescription = new pl.mpak.sky.gui.swing.comp.TextField();

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("table-name-dd")); // NOI18N

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText(stringManager.getString("trigger-name-dd")); // NOI18N

    textName.setText("_TRG");

    checkInactive.setText(stringManager.getString("inactive")); // NOI18N

    groupBA.add(checkBefore);
    checkBefore.setSelected(true);
    checkBefore.setText("BEFORE");

    groupBA.add(checkAfter);
    checkAfter.setText("AFTER");

    groupIUD.add(checkInsert);
    checkInsert.setSelected(true);
    checkInsert.setText("INSERT");

    groupIUD.add(checkUpdate);
    checkUpdate.setText("UPDATE");

    groupIUD.add(checkDelete);
    checkDelete.setText("DELETE");

    textPosition.setText("0");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText(stringManager.getString("order-dd")); // NOI18N

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText(stringManager.getString("description-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboTables, 0, 274, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkInactive)
              .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(checkBefore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAfter))
              .addGroup(layout.createSequentialGroup()
                .addComponent(checkInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDelete))
              .addComponent(textPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(textDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(comboTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkInactive)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkBefore)
          .addComponent(checkAfter))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(checkInsert)
          .addComponent(checkUpdate)
          .addComponent(checkDelete))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(textPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(22, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton checkAfter;
  private javax.swing.JRadioButton checkBefore;
  private javax.swing.JRadioButton checkDelete;
  private javax.swing.JCheckBox checkInactive;
  private javax.swing.JRadioButton checkInsert;
  private javax.swing.JRadioButton checkUpdate;
  private javax.swing.JComboBox comboTables;
  private javax.swing.ButtonGroup groupBA;
  private javax.swing.ButtonGroup groupIUD;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private pl.mpak.sky.gui.swing.comp.TextField textDescription;
  private pl.mpak.sky.gui.swing.comp.TextField textName;
  private pl.mpak.sky.gui.swing.comp.TextField textPosition;
  // End of variables declaration//GEN-END:variables
}
