package pl.mpak.orbada.firebird.gui.wizards;

import javax.swing.DefaultComboBoxModel;
import pl.mpak.orbada.firebird.OrbadaFirebirdPlugin;
import pl.mpak.orbada.firebird.Sql;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.util.QueryUtil;
import pl.mpak.usedb.util.SQLUtil;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class GrantProcedurePrivilegesWizard extends SqlCodeWizardPanel {

  private StringManager stringManager = StringManagerFactory.getStringManager(OrbadaFirebirdPlugin.class);

  private Database database;
  private String objectName;

  public GrantProcedurePrivilegesWizard(Database database, String objectName) {
    this.database = database;
    this.objectName = objectName;
    initComponents();
    init();
  }

  private void init() {
  }
  
  public void wizardShow() {
    Query query = database.createQuery();
    try {
      query.open(Sql.getProcedureNameList());
      comboObjects.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      comboObjects.setSelectedItem(objectName);
      query.open(Sql.getUserNameList());
      comboUsers.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      query.open(Sql.getViewNameList());
      comboViews.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      query.open(Sql.getProcedureNameList());
      comboProcedures.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
      query.open(Sql.getTriggerNameList());
      comboTriggers.setModel(new DefaultComboBoxModel(QueryUtil.queryToArray(query)));
    }
    catch (Exception ex) {
      ExceptionUtil.processException(ex);
    }
    finally {
      query.close();
    }
  }

  public String getDialogTitle() {
    return stringManager.getString("GrantProcedurePrivilegesWizard-dialog-title");
  }

  public String getTabTitle() {
    return stringManager.getString("GrantProcedurePrivilegesWizard-tab-title");
  }

  public String getSqlCode() {
    String object = "";
    if (radioUser.isSelected()) {
      object = SQLUtil.createSqlName(comboUsers.getText());
    }
    else if (radioProcedure.isSelected()) {
      object = "PROCEDURE " +SQLUtil.createSqlName(comboProcedures.getText());
    }
    else if (radioTrigger.isSelected()) {
      object = "TRIGGER " +SQLUtil.createSqlName(comboTriggers.getText());
    }
    else if (radioView.isSelected()) {
      object = "VIEW " +SQLUtil.createSqlName(comboViews.getText());
    }
    return 
      "GRANT EXECUTE ON PROCEDURE " +SQLUtil.createSqlName(comboObjects.getText()) +
      " TO " +object +
      (checkGrantOption.isSelected() ? " WITH GRANT OPTION" : "");
  }

  public boolean execute() {
    try {
      database.executeCommand(getSqlCode());
      return true;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    groupObject = new javax.swing.ButtonGroup();
    jLabel5 = new javax.swing.JLabel();
    comboObjects = new pl.mpak.sky.gui.swing.comp.ComboBox();
    radioUser = new javax.swing.JRadioButton();
    comboUsers = new pl.mpak.sky.gui.swing.comp.ComboBox();
    radioProcedure = new javax.swing.JRadioButton();
    comboProcedures = new pl.mpak.sky.gui.swing.comp.ComboBox();
    comboTriggers = new pl.mpak.sky.gui.swing.comp.ComboBox();
    radioTrigger = new javax.swing.JRadioButton();
    comboViews = new pl.mpak.sky.gui.swing.comp.ComboBox();
    radioView = new javax.swing.JRadioButton();
    checkGrantOption = new javax.swing.JCheckBox();

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText(stringManager.getString("GrantProcedurePrivilegesWizard-privilege-for-object-dd")); // NOI18N

    groupObject.add(radioUser);
    radioUser.setSelected(true);
    radioUser.setText("Dla u¿ytkownika");
    radioUser.setActionCommand(stringManager.getString("GrantProcedurePrivilegesWizard-for-user")); // NOI18N

    comboUsers.setEditable(true);

    groupObject.add(radioProcedure);
    radioProcedure.setText(stringManager.getString("GrantProcedurePrivilegesWizard-for-procedure")); // NOI18N

    groupObject.add(radioTrigger);
    radioTrigger.setText(stringManager.getString("GrantProcedurePrivilegesWizard-for-trigger")); // NOI18N

    groupObject.add(radioView);
    radioView.setText(stringManager.getString("GrantProcedurePrivilegesWizard-for-view")); // NOI18N

    checkGrantOption.setText(stringManager.getString("GrantProcedurePrivilegesWizard-grant-option")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(radioView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboViews, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(radioUser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(radioProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboProcedures, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(radioTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comboTriggers, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(checkGrantOption)
              .addComponent(comboObjects, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(comboObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(checkGrantOption)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioUser)
          .addComponent(comboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioProcedure)
          .addComponent(comboProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioTrigger)
          .addComponent(comboTriggers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(radioView)
          .addComponent(comboViews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkGrantOption;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboObjects;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboProcedures;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboTriggers;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboUsers;
  private pl.mpak.sky.gui.swing.comp.ComboBox comboViews;
  private javax.swing.ButtonGroup groupObject;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JRadioButton radioProcedure;
  private javax.swing.JRadioButton radioTrigger;
  private javax.swing.JRadioButton radioUser;
  private javax.swing.JRadioButton radioView;
  // End of variables declaration//GEN-END:variables

}
