package pl.mpak.orbada.beanshell.gui;

import pl.mpak.orbada.gui.comps.OrbadaJavaSyntaxTextArea;
import pl.mpak.orbada.beanshell.*;
import java.io.File;
import java.io.IOException;
import pl.mpak.orbada.plugins.IApplication;
import pl.mpak.orbada.plugins.ISettingsComponent;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.util.ExceptionUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class StartupShutdownSettingsPanel extends javax.swing.JPanel implements ISettingsComponent {
  
  private final StringManager stringManager = StringManagerFactory.getStringManager(OrbadaBeanshellPlugin.class);

  private IApplication application;
  private File startupFile = OrbadaBeanshellPlugin.getStartupFile();
  private File shutdownFile = OrbadaBeanshellPlugin.getShutdownFile();
  
  /** Creates new form GeneralSettingsProvider */
  public StartupShutdownSettingsPanel(IApplication application) {
    this.application = application;
    initComponents();
    init();
  }
  
  private void init() {
    restoreSettings();
  }
  
  public void restoreSettings() {
    if (startupFile.exists()) {
      try {
        textStartup.loadFromFile(startupFile);
      } catch (IOException ex) {
        ExceptionUtil.processException(ex);
        textStartup.setText("");
      }
    }
    else {
      textStartup.setText("");
    }
    if (shutdownFile.exists()) {
      try {
        textShutdown.loadFromFile(shutdownFile);
      } catch (IOException ex) {
        ExceptionUtil.processException(ex);
        textShutdown.setText("");
      }
    }
    else {
      textShutdown.setText("");
    }
  }

  public void applySettings() {
    try {
      textStartup.saveToFile(startupFile);
      textShutdown.saveToFile(shutdownFile);
    } catch (IOException ex) {
      ExceptionUtil.processException(ex);
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
    }
  }

  public void cancelSettings() {
    restoreSettings();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    textStartup = new OrbadaJavaSyntaxTextArea();
    jLabel2 = new javax.swing.JLabel();
    textShutdown = new OrbadaJavaSyntaxTextArea();

    jLabel1.setText(stringManager.getString("bsh-startup-dd")); // NOI18N

    jLabel2.setText(stringManager.getString("bsh-shutdown-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(textShutdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
          .addComponent(textStartup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textStartup, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(textShutdown, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private OrbadaJavaSyntaxTextArea textShutdown;
  private OrbadaJavaSyntaxTextArea textStartup;
  // End of variables declaration//GEN-END:variables
  
}
