/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QueryCreateTableWizardPanel.java
 *
 * Created on 2009-04-07, 18:28:06
 */
package pl.mpak.orbada.datamove.gui;

import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import pl.mpak.orbada.core.Application;
import pl.mpak.orbada.datamove.OrbadaDataMovePlugin;
import pl.mpak.orbada.db.InternalDatabase;
import pl.mpak.orbada.universal.gui.wizards.SqlCodeWizardPanel;
import pl.mpak.sky.gui.mr.ModalResult;
import pl.mpak.sky.gui.swing.MessageBox;
import pl.mpak.usedb.core.Database;
import pl.mpak.usedb.core.DatabaseManager;
import pl.mpak.usedb.core.Query;
import pl.mpak.usedb.util.QueryUtil;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author akaluza
 */
public class QueryCreateTableWizardPanel extends SqlCodeWizardPanel {

  private final static StringManager stringManager = StringManagerFactory.getStringManager("data-move");

  private Query query;

  /** Creates new form QueryCreateTableWizardPanel */
  public QueryCreateTableWizardPanel(Query query) {
    this.query = query;
    initComponents();
  }

  @Override
  public void wizardShow() {
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    for (int i=0; i<DatabaseManager.getManager().getDatabaseCount(); i++) {
      Database database = DatabaseManager.getManager().getDatabase(i);
      if (!database.equals(InternalDatabase.get()) || Application.get().isUserAdmin()) {
        model.addElement(database);
      }
    }
    comboConnections.setModel(model);
    comboConnections.setRenderer(new DefaultListCellRenderer() {
      public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel label = (JLabel)super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value != null) {
          Database database = (Database)value;
          String text = "<html>";
          if (database.getPublicName() == null) {
            text = text +"<b>" +database.getUserName() +"</b>";
          } else {
            text = text +"<b>" +database.getPublicName() +"</b> as " +database.getUserName();
          }
          //text = text +" (" +(database.getUrl().length() > 40 ? database.getUrl().substring(0, 39) +"..." : database.getUrl()) +")";
          label.setText(text);
          label.setVerticalAlignment(JLabel.TOP);
        }
        return label;
      }
    });
  }

  @Override
  public String getDialogTitle() {
    return stringManager.getString("qctwp-create-table-command");
  }

  @Override
  public String getTabTitle() {
    return stringManager.getString("table");
  }

  @Override
  public String getSqlCode() {
    try {
      return QueryUtil.queryToCreateTable(query, (Database)comboConnections.getSelectedItem(), textTableName.getText(), textQuotedChar.getText());
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return "";
    }
  }

  @Override
  public boolean execute() {
    try {
      if (comboConnections.getSelectedItem() instanceof Database) {
        Database database = (Database)comboConnections.getSelectedItem();
        database.executeCommand(getSqlCode());
        return true;
      }
      return false;
    } catch (Exception ex) {
      MessageBox.show(this, stringManager.getString("error"), ex.getMessage(), ModalResult.OK, MessageBox.ERROR);
      return false;
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    textTableName = new pl.mpak.sky.gui.swing.comp.TextField();
    jLabel2 = new javax.swing.JLabel();
    textQuotedChar = new pl.mpak.sky.gui.swing.comp.ComboBox();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    comboConnections = new pl.mpak.sky.gui.swing.comp.ComboBox();

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText(stringManager.getString("qctwp-table-name-dd")); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText(stringManager.getString("qctwp-table-name-char-dd")); // NOI18N

    textQuotedChar.setEditable(true);
    textQuotedChar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"", "'", "`" }));

    jLabel3.setText(stringManager.getString("qctwp-ext-info-html")); // NOI18N

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText(stringManager.getString("qctwp-dest-connection-dd")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(comboConnections, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
              .addComponent(textTableName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
              .addComponent(textQuotedChar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(textTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(textQuotedChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboConnections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pl.mpak.sky.gui.swing.comp.ComboBox comboConnections;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private pl.mpak.sky.gui.swing.comp.ComboBox textQuotedChar;
  private pl.mpak.sky.gui.swing.comp.TextField textTableName;
  // End of variables declaration//GEN-END:variables
}
