/*
 * GeneralSettingsProvider.java
 *
 * Created on 10 grudzieñ 2007, 20:05
 */

package pl.mpak.orbada.firebird.gui;

import pl.mpak.orbada.firebird.OrbadaFirebirdPlugin;
import pl.mpak.orbada.firebird.services.FirebirdGeneralSettingsProvider;
import pl.mpak.orbada.plugins.IApplication;
import pl.mpak.orbada.plugins.ISettings;
import pl.mpak.orbada.plugins.ISettingsComponent;
import pl.mpak.util.StringManager;
import pl.mpak.util.StringManagerFactory;

/**
 *
 * @author  akaluza
 */
public class GeneralSettingsPanel extends javax.swing.JPanel implements ISettingsComponent {
  
  private StringManager stringManager = StringManagerFactory.getStringManager("firebird");

  private IApplication application;
  private ISettings settings;
  
  /** Creates new form GeneralSettingsProvider */
  public GeneralSettingsPanel(IApplication application) {
    this.application = application;
    initComponents();
    init();
  }
  
  private void init() {
    settings = application.getSettings(FirebirdGeneralSettingsProvider.settingsName);
    restoreSettings();
  }
  
  public void restoreSettings() {
    checkConnectionTransaction.setSelected(settings.getValue(FirebirdGeneralSettingsProvider.SET_ConnectionTransaction, checkConnectionTransaction.isSelected()));
  }

  public void applySettings() {
    settings.setValue(FirebirdGeneralSettingsProvider.SET_ConnectionTransaction, checkConnectionTransaction.isSelected());
    settings.store();
  }

  public void cancelSettings() {
    restoreSettings();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    checkConnectionTransaction = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();

    checkConnectionTransaction.setText(stringManager.getString("GeneralSettingsPanel-checkConnectionTransaction-text")); // NOI18N

    jLabel1.setText(stringManager.getString("GeneralSettingsPanel-checkConnectionTransaction-info")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
          .addComponent(checkConnectionTransaction))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkConnectionTransaction)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addContainerGap(207, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkConnectionTransaction;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
}
